import { PoeItem } from '../poe.types.js';
export const elementalBow = {
	baseType: 'Decimation Bow',
	explicitMods: [
		'Adds 85 to 176 Fire Damage',
		'Adds 101 to 156 Cold Damage',
		'Adds 3 to 47 Lightning Damage',
		'+24% to Global Critical Strike Multiplier',
	],
	frameType: 2,
	h: 4,
	icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Cb3dzL0JvdzgiLCJ3IjoyLCJoIjo0LCJzY2FsZSI6MX1d/8d079c60ed/Bow8.png',
	id: 'a554ec0f46a4801ef9115d6ff87e7816b1523e6b3b98c80db138d7930feee002',
	identified: true,
	ilvl: 55,
	implicitMods: ['46% increased Critical Strike Chance'],
	inventoryId: 'Stash1',
	league: 'Standard',
	name: 'Foe Volley',
	note: '~b/o 2 chaos',
	properties: [
		{ displayMode: 0, name: 'Bow', values: [] },
		{ displayMode: 0, name: 'Physical Damage', type: 9, values: [['44-116', 0]] },
		{
			displayMode: 0,
			name: 'Elemental Damage',
			type: 10,
			values: [
				['85-176', 4],
				['101-156', 5],
				['3-47', 6],
			],
		},
		{ displayMode: 0, name: 'Critical Strike Chance', type: 12, values: [['7.30%', 1]] },
		{ displayMode: 0, name: 'Attacks per Second', type: 13, values: [['1.20', 0]] },
	],
	rarity: 'Rare',
	requirements: [
		{ displayMode: 0, name: 'Level', type: 62, values: [['53', 0]] },
		{ displayMode: 1, name: 'Dex', type: 64, values: [['170', 0]] },
	],
	socketedItems: [],
	sockets: [
		{ attr: 'D', group: 0, sColour: 'G' },
		{ attr: 'D', group: 0, sColour: 'G' },
		{ attr: 'D', group: 0, sColour: 'G' },
		{ attr: 'D', group: 0, sColour: 'G' },
	],
	typeLine: 'Decimation Bow',
	verified: false,
	w: 2,
	x: 9,
	y: 4,
} as PoeItem;
