import { PoeItem } from '../poe.types.js';
/**
 * Fractured gloves.
 * Sungeego profile
 * https://www.pathofexile.com/account/view-profile/Sungeego/characters?characterName=%D1%85_%D1%82%D1%80%D1%83%D0%BA%D1%81%D1%82%D0%B8%D1%80_%D1%85
 */
export const fracturedGloves = {
	verified: false,
	w: 2,
	h: 2,
	icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQXJtb3Vycy9HbG92ZXMvR2xvdmVzRGV4SW50MyIsInciOjIsImgiOjIsInNjYWxlIjoxLCJzZWFyaW5nIjp0cnVlLCJ0YW5nbGVkIjp0cnVlLCJmcmFjdHVyZWQiOnRydWV9XQ/d75e38f086/GlovesDexInt3.png',
	league: 'Standard',
	id: '4847194b354cdbfb9a9e818344677a13f76c87468d1e4f86829d4f8c57997ef2',
	searing: true,
	tangled: true,
	fractured: true,
	sockets: [
		{
			group: 0,
			attr: 'G',
			sColour: 'W',
		},
		{
			group: 0,
			attr: 'I',
			sColour: 'B',
		},
		{
			group: 0,
			attr: 'I',
			sColour: 'B',
		},
		{
			group: 0,
			attr: 'G',
			sColour: 'W',
		},
	],
	name: 'Rapture Caress',
	typeLine: 'Murder Mitts',
	baseType: 'Murder Mitts',
	rarity: 'Rare',
	ilvl: 85,
	identified: true,
	properties: [
		{
			name: 'Quality',
			values: [['+20%', 1]],
			displayMode: 0,
			type: 6,
		},
		{
			name: 'Evasion Rating',
			values: [['174', 1]],
			displayMode: 0,
			type: 17,
		},
		{
			name: 'Energy Shield',
			values: [['36', 1]],
			displayMode: 0,
			type: 18,
		},
	],
	requirements: [
		{
			name: 'Level',
			values: [['72', 0]],
			displayMode: 0,
			type: 62,
			suffix: '(gem)',
		},
		{
			name: 'Dex',
			values: [['111', 0]],
			displayMode: 1,
			type: 64,
			suffix: '(gem)',
		},
		{
			name: 'Int',
			values: [['159', 0]],
			displayMode: 1,
			type: 65,
			suffix: '(gem)',
		},
	],
	implicitMods: [
		'Inflict Lightning Exposure on Hit, applying -12% to Lightning Resistance',
		'20% chance to Intimidate Enemies for 4 seconds on Hit',
	],
	explicitMods: [
		'16% increased Attack Speed',
		'24% increased Evasion and Energy Shield',
		'+80 to maximum Life',
		'+46% to Lightning Resistance',
		'11% increased Stun and Block Recovery',
	],
	craftedMods: ['28% increased Damage during any Flask Effect'],
	fracturedMods: ['+12% chance to Suppress Spell Damage'],
	frameType: 2,
	x: 0,
	y: 0,
	inventoryId: 'Gloves',
	socketedItems: [
		{
			verified: false,
			w: 1,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L01hcmtPbkhpdHRpbmciLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/082becefa3/MarkOnHitting.png',
			support: true,
			league: 'Standard',
			id: 'f0d13bbb26e9082738280f8e01f252c79b086523d1ca791bc2e328971dd84ca9',
			name: '',
			typeLine: 'Mark On Hit Support',
			baseType: 'Mark On Hit Support',
			ilvl: 0,
			identified: true,
			properties: [
				{
					name: 'Support, Mark, Trigger',
					values: [],
					displayMode: 0,
				},
				{
					name: 'Level',
					values: [['20 (Max)', 0]],
					displayMode: 0,
					type: 5,
				},
				{
					name: 'Cost & Reservation Multiplier',
					values: [['200%', 0]],
					displayMode: 0,
				},
				{
					name: 'Cooldown Time',
					values: [['4.00 sec', 0]],
					displayMode: 0,
				},
				{
					name: 'Quality',
					values: [['+20%', 1]],
					displayMode: 0,
					type: 6,
				},
			],
			requirements: [
				{
					name: 'Level',
					values: [['70', 0]],
					displayMode: 0,
					type: 62,
				},
				{
					name: 'Dex',
					values: [['111', 0]],
					displayMode: 1,
					type: 64,
				},
			],
			secDescrText: 'Supports mark curse skills.',
			explicitMods: [
				'16% reduced Effect of Marks from Supported Skills',
				'Trigger Supported Skill when you Hit a Rare or Unique Enemy with an Attack',
			],
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			frameType: 4,
			socket: 0,
			colour: 'D',
		},
		{
			verified: false,
			w: 1,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzMwLDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9Bc3Nhc3NpbnNNYXJrIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/4d097e1260/AssassinsMark.png',
			support: false,
			league: 'Standard',
			id: 'f02926a4129e7696b2ece10bb8912e4309d9c2e6be3f9cfe6e3c2f197f6ba36e',
			name: '',
			typeLine: "Assassin's Mark",
			baseType: "Assassin's Mark",
			ilvl: 0,
			identified: true,
			corrupted: true,
			properties: [
				{
					name: 'Critical, Spell, Curse, Mark',
					values: [],
					displayMode: 0,
				},
				{
					name: 'Level',
					values: [['21 (Max)', 0]],
					displayMode: 0,
					type: 5,
				},
				{
					name: 'Cost',
					values: [['34 Mana', 0]],
					displayMode: 0,
				},
				{
					name: 'Cast Time',
					values: [['0.50 sec', 0]],
					displayMode: 0,
				},
				{
					name: 'Quality',
					values: [['+20%', 1]],
					displayMode: 0,
					type: 6,
				},
			],
			requirements: [
				{
					name: 'Level',
					values: [['72', 0]],
					displayMode: 0,
					type: 62,
				},
				{
					name: 'Dex',
					values: [['70', 0]],
					displayMode: 1,
					type: 64,
				},
				{
					name: 'Int',
					values: [['100', 0]],
					displayMode: 1,
					type: 65,
				},
			],
			secDescrText:
				'Curses a single enemy, making them more vulnerable to Critical Strikes. Killing the cursed enemy will grant life and mana, and a power charge. You can only have one Mark at a time.',
			explicitMods: [
				'Cursed enemies have a 100% chance to grant a Power Charge when slain',
				'Hits against Cursed Enemies have +1.5% to Critical Strike Chance',
				'Hits against Cursed Enemies have +50% to Critical Strike Multiplier',
				'Cursed enemies grant 623 Life when Killed',
				'Cursed enemies grant 82 Mana when Killed',
				'Cursed Enemies have a 5% chance to grant a Power Charge when Hit',
			],
			descrText:
				'Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.',
			frameType: 4,
			socket: 1,
			colour: 'I',
		},
		{
			verified: false,
			w: 1,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzMwLDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdG9ybUJsYWRlR2VtIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/aa45718a55/StormBladeGem.png',
			support: false,
			league: 'Standard',
			id: '398edf6ac9d952d9a51c05fae92c21c213eadba8ce3436a457923e85ffb18ecf',
			name: '',
			typeLine: 'Energy Blade',
			baseType: 'Energy Blade',
			ilvl: 0,
			identified: true,
			corrupted: true,
			properties: [
				{
					name: 'Spell, Lightning',
					values: [],
					displayMode: 0,
				},
				{
					name: 'Level',
					values: [['21 (Max)', 0]],
					displayMode: 0,
					type: 5,
				},
				{
					name: 'Cost',
					values: [['702 Energy Shield', 0]],
					displayMode: 0,
				},
				{
					name: 'Cooldown Time',
					values: [['1.00 sec', 0]],
					displayMode: 0,
				},
				{
					name: 'Cast Time',
					values: [['1.00 sec', 0]],
					displayMode: 0,
				},
				{
					name: 'Quality',
					values: [['+20%', 1]],
					displayMode: 0,
					type: 6,
				},
			],
			requirements: [
				{
					name: 'Level',
					values: [['72', 0]],
					displayMode: 0,
					type: 62,
				},
				{
					name: 'Int',
					values: [['159', 0]],
					displayMode: 1,
					type: 65,
				},
			],
			secDescrText:
				'Grants a buff which significantly lowers your maximum Energy Shield to transform your equipped weapons into Swords formed from that energy. Casting the spell again removes the buff. Requires a Non-Bow weapon. This skill cannot be triggered.',
			explicitMods: [
				'Energy Blades have minimum Lightning Damage equal to 2% of Energy Shield, plus 13\nEnergy Blades have maximum Lightning Damage equal to 40% of Energy Shield, plus 250',
				'Two Handed Energy Blades have 70% more Lightning Damage',
				'Buff grants 45% less Maximum Energy Shield',
			],
			descrText:
				'Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.',
			frameType: 4,
			socket: 2,
			colour: 'I',
		},
		{
			verified: false,
			w: 1,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L2VuaGFuY2UiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/9f8df30377/enhance.png',
			support: true,
			league: 'Standard',
			id: '98746c05e66376dec1cc4afa1d0a7fceda5548dae299f8b6033b91a5a5d52e4d',
			name: '',
			typeLine: 'Enhance Support',
			baseType: 'Enhance Support',
			ilvl: 0,
			identified: true,
			corrupted: true,
			properties: [
				{
					name: 'Exceptional, Support',
					values: [],
					displayMode: 0,
				},
				{
					name: 'Level',
					values: [['4 (Max)', 0]],
					displayMode: 0,
					type: 5,
				},
				{
					name: 'Cost & Reservation Multiplier',
					values: [['120%', 0]],
					displayMode: 0,
				},
			],
			requirements: [
				{
					name: 'Level',
					values: [['60', 0]],
					displayMode: 0,
					type: 62,
				},
				{
					name: 'Dex',
					values: [['96', 0]],
					displayMode: 1,
					type: 64,
				},
			],
			secDescrText:
				"Supports any skill gem. Once this gem reaches level 2 or above, will raise the quality of supported gems. Cannot support skills that don't come from gems.",
			explicitMods: ['+24% to Quality of Supported Skill Gems'],
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			frameType: 4,
			socket: 3,
			colour: 'D',
		},
	],
} as PoeItem;
