import { PoeItem } from '../poe.types.js';
export const socketed = {
	baseType: "Assassin's Garb",
	explicitMods: [
		'131% increased Evasion Rating',
		'+25% to Chaos Resistance',
		'You can apply an additional Curse',
		'Your Hexes can affect Hexproof Enemies',
		'Poison Cursed Enemies on hit',
	],
	flavourText: [
		'Curse their vile Council,\r',
		'They cast me aside as if I am some bastard child.\r',
		'If they only knew the power I possess.',
	],
	frameType: 3,
	h: 3,
	icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQXJtb3Vycy9Cb2R5QXJtb3Vycy9Db3NwcmlzV2lsbCIsInciOjIsImgiOjMsInNjYWxlIjoxfV0/e7801b1322/CosprisWill.png',
	id: '138b9f17f038b306c48cd7b667b5307d496f9ce5d7c5162d1ad09ad6a7b4dd02',
	identified: true,
	ilvl: 73,
	implicitMods: ['3% increased Movement Speed'],
	inventoryId: 'Stash1',
	league: 'Standard',
	name: "Cospri's Will",
	properties: [
		{
			displayMode: 0,
			name: 'Quality',
			type: 6,
			values: [['+20%', 1]],
		},
		{
			displayMode: 0,
			name: 'Evasion Rating',
			type: 17,
			values: [['1850', 1]],
		},
	],
	rarity: 'Unique',
	requirements: [
		{
			displayMode: 0,
			name: 'Level',
			type: 62,
			values: [['68', 0]],
		},
		{
			displayMode: 1,
			name: 'Dex',
			type: 64,
			values: [['183', 0]],
		},
		{
			displayMode: 1,
			name: 'Int',
			suffix: '(gem)',
			type: 65,
			values: [['102', 0]],
		},
	],
	socketedItems: [
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.18,
					type: 20,
					values: [['7942261/43867388', 0]],
				},
			],
			baseType: 'Increased Critical Strikes Support',
			colour: 'I',
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			explicitMods: [
				'Supported Skills have 111% increased Critical Strike Chance',
				'Supported Skills have +2% to Critical Strike Chance',
			],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L0luY3JlYXNlZENyaXRpY2FsU3RyaWtlcyIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/afc7a604cf/IncreasedCriticalStrikes.png',
			id: '115eb387546c37255f7be44836287e469ee2cb3d4d690ff969e227e32724b349',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Critical, Support',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['18', 0]],
				},
				{
					displayMode: 0,
					name: 'Cost & Reservation Multiplier',
					values: [['120%', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['64', 0]],
				},
				{
					displayMode: 1,
					name: 'Int',
					type: 65,
					values: [['102', 0]],
				},
			],
			secDescrText: 'Supports any skill that hits enemies.',
			socket: 0,
			support: true,
			typeLine: 'Increased Critical Strikes Support',
			verified: false,
			w: 1,
		},
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.78,
					type: 20,
					values: [['19424241/25050611', 0]],
				},
			],
			baseType: 'Void Manipulation Support',
			colour: 'D',
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			explicitMods: ['Supported Skills deal 32% more Chaos Damage', 'Supported Skills deal no Elemental Damage'],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L1ZvaWRNYW5pcHVsYXRpb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/d43a79f597/VoidManipulation.png',
			id: '3a09a42c41cd3990955cacff27d3983134c94b7104da484b2dd4054c4f1a5a5e',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Chaos, Support',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['17', 0]],
				},
				{
					displayMode: 0,
					name: 'Cost & Reservation Multiplier',
					values: [['130%', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['61', 0]],
				},
				{
					displayMode: 1,
					name: 'Dex',
					type: 64,
					values: [['61', 0]],
				},
				{
					displayMode: 1,
					name: 'Int',
					type: 65,
					values: [['43', 0]],
				},
			],
			secDescrText: 'Supports any skill that deals damage.',
			socket: 1,
			support: true,
			typeLine: 'Void Manipulation Support',
			verified: false,
			w: 1,
		},
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.22,
					type: 20,
					values: [['9481304/43869436', 0]],
				},
			],
			baseType: 'Pierce Support',
			colour: 'D',
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			explicitMods: [
				'Projectiles from Supported Skills Pierce 4 additional Targets',
				'Supported Skills deal 17% more Projectile Damage',
			],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L1BpZXJjZSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/9cceecca83/Pierce.png',
			id: '3181d98780623f98c76bed55c00ffef6a3e06c516275f9f7886aa25cb75117f8',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Support, Projectile',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['18', 0]],
				},
				{
					displayMode: 0,
					name: 'Cost & Reservation Multiplier',
					values: [['120%', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['64', 0]],
				},
				{
					displayMode: 1,
					name: 'Dex',
					type: 64,
					values: [['102', 0]],
				},
			],
			secDescrText: 'Supports projectile skills.',
			socket: 2,
			support: true,
			typeLine: 'Pierce Support',
			verified: false,
			w: 1,
		},
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.23,
					type: 20,
					values: [['10060855/43869739', 0]],
				},
			],
			baseType: 'Caustic Arrow',
			colour: 'D',
			descrText:
				'Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.',
			explicitMods: [
				'Deals 1327.6 Base Chaos Damage per second',
				'Base duration is 2.00 seconds',
				'60% of Physical Damage Converted to Chaos Damage',
				"Modifiers to Projectile Damage apply to this Skill's Damage Over Time effect",
				'+0.5 metres to radius',
			],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzMwLDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9Qb2lzb25BcnJvdyIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/d9f7c19c93/PoisonArrow.png',
			id: '52ce0b7a6600e42e693b8bd6116e04424989c68e367ffb6f793b36ad6470f4c3',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Attack, Projectile, AoE, Duration, Chaos, Bow',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['18', 0]],
				},
				{
					displayMode: 0,
					name: 'Cost',
					values: [['10 Mana', 0]],
				},
				{
					displayMode: 0,
					name: 'Attack Damage',
					values: [['63.4% of base', 0]],
				},
				{
					displayMode: 0,
					name: 'Effectiveness of Added Damage',
					values: [['63%', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['64', 0]],
				},
				{
					displayMode: 1,
					name: 'Dex',
					type: 64,
					values: [['142', 0]],
				},
			],
			secDescrText:
				'Fires an arrow which deals chaos damage in an area on impact, and spreads caustic ground. Enemies standing on the caustic ground take chaos damage over time.',
			socket: 3,
			support: false,
			typeLine: 'Caustic Arrow',
			verified: false,
			w: 1,
		},
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.95,
					type: 20,
					values: [['24894169/26260555', 0]],
				},
			],
			baseType: 'Vicious Projectiles Support',
			colour: 'D',
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			explicitMods: [
				'Supported Skills deal 46% more Chaos Damage over Time',
				'Supported Skills deal 46% more Physical Damage over Time',
				'Supported Skills deal 46% more Physical Projectile Attack Damage',
				'Supported Skills have 10% less Projectile Attack Speed',
			],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L1JhbmdlZFBoeXNpY2FsQXR0YWNrRGFtYWdlIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/ad10efb4f6/RangedPhysicalAttackDamage.png',
			id: '3a4ea7ba8908f073cdce2409fcfed0bb3ccdd09f2064998b810ebb87f25d431c',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Projectile, Attack, Physical, Chaos, Support',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['17', 0]],
				},
				{
					displayMode: 0,
					name: 'Cost & Reservation Multiplier',
					values: [['130%', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['64', 0]],
				},
				{
					displayMode: 1,
					name: 'Dex',
					type: 64,
					values: [['102', 0]],
				},
			],
			secDescrText: 'Supports projectile attack skills.',
			socket: 4,
			support: true,
			typeLine: 'Vicious Projectiles Support',
			verified: false,
			w: 1,
		},
		{
			additionalProperties: [
				{
					displayMode: 2,
					name: 'Experience',
					progress: 0.76,
					type: 20,
					values: [['19697401/25964218', 0]],
				},
			],
			baseType: 'Blasphemy Support',
			colour: 'I',
			descrText:
				'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
			explicitMods: [
				'Supported Curse Skills apply their Curses as Auras\nSupported Curse Skills also count as Aura Skills',
				'Using Supported Skills is Instant',
				'25% less Effect of Supported Curses',
				'64% increased Area of Effect of Supported Curse Skills',
			],
			frameType: 4,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L0F1cmlmeSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/ac2d013ed8/Aurify.png',
			id: '74d95eafd4f6321e6e8affe5f6a0d833afa5a8f407e3effbab8f284d5009b81d',
			identified: true,
			ilvl: 0,
			league: 'Standard',
			name: '',
			properties: [
				{
					displayMode: 0,
					name: 'Support, Hex, Aura',
					values: [],
				},
				{
					displayMode: 0,
					name: 'Level',
					type: 5,
					values: [['17', 0]],
				},
				{
					displayMode: 0,
					name: 'Reservation Override',
					values: [['35% Mana', 0]],
				},
				{
					displayMode: 0,
					name: 'Cooldown Time',
					values: [['1.20 sec', 0]],
				},
			],
			requirements: [
				{
					displayMode: 0,
					name: 'Level',
					type: 62,
					values: [['64', 0]],
				},
				{
					displayMode: 1,
					name: 'Int',
					type: 65,
					values: [['102', 0]],
				},
			],
			secDescrText:
				'Supports hex curse skills, turning them into auras that will apply their effect to all enemies in an area around you.',
			socket: 5,
			support: true,
			typeLine: 'Blasphemy Support',
			verified: false,
			w: 1,
		},
	],
	sockets: [
		{
			attr: 'I',
			group: 0,
			sColour: 'B',
		},
		{
			attr: 'D',
			group: 0,
			sColour: 'G',
		},
		{
			attr: 'D',
			group: 0,
			sColour: 'G',
		},
		{
			attr: 'D',
			group: 0,
			sColour: 'G',
		},
		{
			attr: 'D',
			group: 0,
			sColour: 'G',
		},
		{
			attr: 'I',
			group: 1,
			sColour: 'B',
		},
	],
	typeLine: "Assassin's Garb",
	verified: false,
	w: 2,
	x: 6,
	y: 5,
} as PoeItem;
