pub const ACT_AREA_NAMES: &'static [&'static str] = &[
    "Chamber of Innocence (A5/A10)",
    "Chamber of Sins Level 1/2 (Act 7)",
    "Control BLocks",
    "Daresso's Dream",
    "Kaom's Dream",
    "Kaom's Stronghold",
    "Lower Prison (Act 6)",
    "Lunaris Temple Level 1/2 (A8)",
    "Maligaro's Sanctum",
    "Oriath Square",
    "Prisoner's Gate (A6)",
    "Reliquary",
    "Shavronne's Tower",
    "The Ancient Pyramid",
    "The Aqueduct",
    "The Archives",
    "The Ascent",
    "The Ashen Fields",
    "The Bath House",
    "The Battlefront",
    "The Beacon",
    "The Belly of the Beast",
    "The Belly of the Beast (A4/9)",
    "The Belly of the Beast (A4/A9)",
    "The Blood Aqueduct",
    "The Boiling Lake",
    "The Broken Bridge",
    "The Catacombs",
    "The Cathedral Rooftop (A5)",
    "The Causeway",
    "The Cavern of Anger (Act 6)",
    "The Chamber of Innocence",
    "The Chamber of Sins Level 1 (Act 7)",
    "The Chamber of Sins Level 1/2 (Act 7)",
    "The City of Sarn",
    "The Coast (A6)",
    "The Control Blocks",
    "The Control Blocks (Act 5)",
    "The Crematorium",
    "The Crossroads",
    "The Crossroads (A7)",
    "The Crossroads (Act 7)",
    "The Crypt",
    "The Crypt (Act 7)",
    "The Crystal Veins",
    "The Den (Act 7)",
    "The Descent",
    "The Desecrated Chambers",
    "The Docks",
    "The Dread Thicket (A7)",
    "The Ebony Barracks",
    "The Feeding Trough",
    "The Fellshrine Ruins",
    "The Fellshrine Ruins (A7)",
    "The Foothills",
    "The Grain Gate",
    "The Grand Arena",
    "The Grand Promenade",
    "The Harbour Bridge",
    "The Harbour Bridge, The Solaris Temple Level 2 (Act 8)",
    "The Harvest",
    "The High Gardens",
    "The Imperial Fields",
    "The Imperial Gardens",
    "The Karui Fortress",
    "The Library",
    "The Lower Prison (Act 6)",
    "The Lunaris Concourse",
    "The Lunaris Temple Level 2 (Act 3)",
    "The Lunaris Temple Level 2 (Act 8)",
    "The Marketplace",
    "The Mines Level 1",
    "The Mines Level 2",
    "The Mud Flats (A6)",
    "The Mud Flats (Act 6)",
    "The Northern Forest",
    "The Northern Forest (A7)",
    "The Oasis",
    "The Ossuary",
    "The Ossuary (Act 10)",
    "The Ossuary (Act 5)",
    "The Ossuary (Act 5/10)",
    "The Quarry",
    "The Quay",
    "The Ravaged Square",
    "The Refinery",
    "The Reliquary",
    "The Reliquary (Act 5/10)",
    "The Riverways (Act 6)",
    "The Rotting Core",
    "The Ruined Square",
    "The Sarn Ramparts",
    "The Sceptre of God",
    "The Sewers",
    "The Slave Pens",
    "The Slums",
    "The Solaris Concourse",
    "The Solaris Temple 1/2 (A8)",
    "The Solaris Temple Level 1 (A3)",
    "The Solaris Temple Level 1 (Act 8)",
    "The Solaris Temple Level 2 (Act 8)",
    "The Southern Forest (Act 6)",
    "The Temple of Decay Level 1",
    "The Temple of Decay Level 1/2",
    "The Temple of Decay Level 2",
    "The Tidal Island (A6)",
    "The Torched Courts (A5/10)",
    "The Toxic Conduits",
    "The Tunnel",
    "The Twilight Strand (A6)",
    "The Upper Sceptre of God",
    "The Vaal City",
    "The Vasitri Desert",
    "The Vastiri Desert",
];
