packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
allowBuilds:
  wasm-pack: true
catalog:
  "@shoelace-style/shoelace": ^2.20
  "@types/node": ^25
  lit: ^3.3.2
  poe-custom-elements: latest
  typescript: ^6.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-static-copy: ^4
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
