packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
allowBuilds:
  esbuild: true
  rs-module-lexer: true
  wasm-pack: true
minimumReleaseAgeExclude:
  - poe-custom-elements
catalog:
  "@tauri-apps/api": ^2
  "@tauri-apps/cli": ^2
  "@tauri-apps/plugin-process": ^2
  "@tauri-apps/plugin-updater": ^2
  poe-custom-elements: latest
  "@shoelace-style/shoelace": ^2.20
  "@types/node": ^25
  lit: ^3.3.2
  typescript: ^6.0
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-static-copy: ^4
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  "@voidzero-dev/vite-plus-core": "npm:@voidzero-dev/vite-plus-core@0.3.0"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
