[package]
name = "fs_cache_fetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project-root = "0.2.2"
serde = {workspace = true} 
serde_json = {workspace = true} 
