pub const BOSS_NAMES: &'static [&'static str] = &[
    "Thorn",
    "Fairgraves, Never Dying",
    "Tormented Temptress (Whakawairua Tuahu)",
    "Avatar of the Huntress",
    "Rose",
    "Nightmare's Omen",
    "Caer Blaidd, Wolfpack's Den",
    "Helial, the Day Unending",
    "Ghorr, the Grasping Maw",
    "The Vindicated Queen",
    "Kurgal, the Blackblooded",
    "Aul, the Crystal King",
    "The Infinite Hunger",
    "Fenumus, First of the Night",
    "Infector of Dreams",
    "Tahsin, Warmaker",
    "Stone of the Currents",
    "Nightmare's Omen",
    "Fragment of Winter",
    "Gorulis, Will-Thief (Infested Valley)",
    "Titan of the Grove",
    "Calderus",
    "Avatar of the Skies",
    "Avatar of Undoing",
    "Varhesh, Shimmering Aberration",
    "Erebix, Light's Bane",
    "Lord of the Hollows",
    "Messenger of the Hollows",
    "Champion of the Hollows",
    "Entity of the Void",
    "Opid, Helial's Herald",
    "Skullbeak",
    "Headmistress Braeta",
    "Eyepecker",
    "Gorulis, Will-Thief",
    "Mephod, the Earth Scorcher",
    "Ara, Sister of Light",
    "Flesh Sculptor",
    "Corpse Stitcher",
    "Nightwane",
    "The Animal Pack",
    "Stonebeak, Battle Fowl",
    "Jorus, Sky's Edge",
    "Shrieker Eihal",
    "Gisale, Thought Thief",
    "K'aj Y'ara'az",
    "Uul-Netol, Unburdened Flesh",
    "Olof, Son of the Headsman",
    "Chayula, Who Dreamt",
    "Farrul, First of the Plains",
    "Uhtred, Covetous Traitor",
    "Omniphobia, Fear Manifest",
    "Kosis, The Revelation",
    "Merveil, the Reflection (Underground Sea)",
    "Avatar of the Forge",
    "Eater of Souls",
    "The Cleansing Light",
    "Xixic, High Necromancer",
    "Armala, the Widow",
    "Ambrius, Legion Slayer",
    "Drek, Apex Hunter",
    "Bazur",
    "Prodigy of Darkness",
    "Shavronne the Sickening",
    "Amalgam of Nightmares",
    "Leo, Wolf of the Pits",
    "The High Templar",
    "The Bone Sculptor",
    "The Maven",
    "Oshabi, Avatar of the Grove",
    "Beast of the Pits",
    "Tolman, the Exhumer",
    "Burtok, Shaper of Bones",
    "K'aj Q'ura",
    "The Brittle Emperor",
    "Uber Elder",
    "The Searing Exarch",
    "Catarina, Master of Undeath",
    "Gnar, Eater of Carrion",
    "Argus",
    "The Hallowed Husk",
    "The Cursed King",
    "The Eater of Worlds",
    "Drought-Maddened Rhoa",
    "Doedre the Defiler",
    "Khor, Sister of Shadows",
    "Murgeth Bogsong",
    "Stalker of the Endless Dunes",
    "Telvar, the Inebriated",
    "Nassar, Lion of the Seas",
    "Venarius",
    "Void Anomaly",
    "Maligaro the Mutilator",
    "Merveil, the Returned",
    "The Elder",
    "Ryslatha, the Puppet Mistress",
    "Voll, Emperor of Purity",
    "Portentia, the Foul",
    "Portentia, the Foul (Waste Pool)",
    "Erythrophagia (Phantasmagoria)",
    "Erythrophagia",
    "Hephaeus, The Hammer",
    "Selenia, the Endless Night",
    "The Brine King's Reef",
    "K'tash, the Hate Shepherd",
    "Prodigy of Hexes",
    "Excellis Aurafix",
    "Guardian of the Vault",
    "Terror of the Infinite Drifts",
    "The Eroding One",
    "The Winged Death",
    "Elida Blisterclaw (Bramble Valley)",
    "Fire and Fury (Lava Chamber)",
    "Merveil, the Reflection (Maelstrom of Chaos)",
    "Shock and Horror (Mineral Pools)",
    "Steelpoint the Avenger",
    "The Sanguine Siren",
    "K'aj A'alai (Vaal Temple Trio)",
    "The Dishonoured Queen",
    "Steelpoint the Avenger",
    "Mirage of Bones",
    "Lord of the Ashen Arrow",
    "Kitava, The Destroyer (The Destroyer's Heart)",
];

pub const AREA_NAMES: &'static [&'static str] = &["The Apex of Sacrifice", "The Alluring Abyss"];

pub const ACT_AREA_NAMES: &'static [&'static str] = &[
    "The Imperial Fields",
    "The Fellshrine Ruins",
    "The Quay",
    "The Ascent",
    "The Causeway",
    "The Grand Arena",
    "Shavronne's Tower",
    "The Sarn Ramparts",
    "The Docks",
    "Oriath Square",
    "The High Gardens",
    "The Slums",
    "The Vastiri Desert",
    "The Feeding Trough",
    "The Oasis",
    "The Ebony Barracks",
    "The Grain Gate",
    "Kaom's Dream",
    "The Lunaris Concourse",
    "The Ancient Pyramid",
    "The Aqueduct",
    "The Grand Promenade",
    "The Boiling Lake",
    "Reliquary",
    "The Catacombs",
    "The Toxic Conduits",
    "The Sewers",
    "The Archives",
    "Daresso's Dream",
    "The Marketplace",
    "The Sceptre of God",
    "The Refinery",
    "The Solaris Temple Level 1 (A3)",
    "The Lunaris Temple Level 2 (Act 3)",
    "The Solaris Concourse",
    "The Mines Level 1",
    "The Mines Level 2",
    "The Belly of the Beast (A4/A9)",
    "The Belly of the Beast (A4/9)",
    "The Belly of the Beast",
    "The Cathedral Rooftop (A5)",
    "The Mud Flats (A6)",
    "The Mud Flats (Act 6)",
    "The Lower Prison (Act 6)",
    "Lower Prison (Act 6)",
    "The Riverways (Act 6)",
    "The Tidal Island (A6)",
    "Prisoner's Gate (A6)",
    "The Twilight Strand (A6)",
    "The Chamber of Sins Level 1 (Act 7)",
    "Chamber of Sins Level 1/2 (Act 7)",
    "The Chamber of Sins Level 1/2 (Act 7)",
    "The Crossroads",
    "The Crossroads (A7)",
    "The Crossroads (Act 7)",
    "The Crypt (Act 7)",
    "The Crypt",
    "The Solaris Temple Level 1 (Act 8)",
    "The Solaris Temple 1/2 (A8)",
    "The Lunaris Temple Level 2 (Act 8)",
    "The Fellshrine Ruins (A7)",
    "The Ossuary (Act 5)",
    "The Ossuary (Act 10)",
    "The Ossuary (Act 5/10)",
    "The Ossuary",
    "Maligaro's Sanctum",
    "The Bath House",
    "The Battlefront",
    "The Ashen Fields",
    "The Beacon",
    "The Blood Aqueduct",
    "The Broken Bridge",
    "Control BLocks",
    "The Control Blocks",
    "The Control Blocks (Act 5)",
    "The Harbour Bridge, The Solaris Temple Level 2 (Act 8)",
    "The Solaris Temple Level 2 (Act 8)",
    "Temple, The Twilight Temple, Cold River, The Solaris Temple Level 1 (Act 8)",
    "The Coast (A6)",
    "The Cavern of Anger (Act 6)",
    "The Southern Forest (Act 6)",
    "The Den (Act 7)",
    "The Torched Courts (A5/10)",
    "Lunaris Temple Level 1/2 (A8)",
    "The Library",
    "The Crystal Veins",
    "The Reliquary",
    "The Reliquary (Act 5/10)",
    "The Desecrated Chambers",
    "The Foothills",
    "The Harbour Bridge",
    "The Ravaged Square",
    "The Ruined Square",
    "The Slave Pens",
    "The Quarry",
    "The Temple of Decay Level 1",
    "The Temple of Decay Level 2",
    "The Temple of Decay Level 1/2",
    "The Vasitri Desert",
    "The Dread Thicket (A7)",
    "The Northern Forest (A7)",
    "Chamber of Innocence (A5/A10)",
    "The Descent",
    "The Crematorium",
    "The Tunnel",
    "The Harvest",
    "The Chamber of Innocence",
    "Kaom's Stronghold",
    "The Northern Forest",
    "The Karui Fortress",
    "The Vaal City",
    "The Imperial Gardens",
    "The Rotting Core",
    "The City of Sarn",
    "The Upper Sceptre of God",
];

pub const CHESTS: &'static [&'static str] = &[
    "Light Jewellery chest (Primeval Ruins, Abyssal City, Vaal Outpost)",
    "Delve Gem Chests",
    "Uber Labyrinth/Enriched Labyrinth (Izaro's Treasure, Labyrinth Trove, Curious Lockbox)",
];
