import { TabWithItems } from '../../poe.types.js';
export const a = {
	id: 'b6ffb9167c',
	index: 0,
	items: [
		{
			baseType: 'Plated Maul',
			craftedMods: ['70% increased Physical Damage'],
			explicitMods: [
				'+17 to Strength',
				'53% increased Physical Damage',
				'Adds 92 to 187 Fire Damage',
				'22% increased Attack Speed',
				'27% increased Stun Duration on Enemies',
				'+104 to Accuracy Rating',
			],
			frameType: 2,
			h: 4,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvV2VhcG9ucy9Ud29IYW5kV2VhcG9ucy9Ud29IYW5kTWFjZXMvVHdvSGFuZE1hY2U2IiwidyI6MiwiaCI6NCwic2NhbGUiOjF9XQ/a114ad5617/TwoHandMace6.png',
			id: '152ae699ec8c3e108689709c5aee6e36df7889533811335a921d8f5d3565ed2e',
			identified: true,
			ilvl: 58,
			implicitMods: ['30% increased Stun Duration on Enemies'],
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			name: 'Honour Mangler',
			properties: [
				{ displayMode: 0, name: 'Two Handed Mace', values: [] },
				{ displayMode: 0, name: 'Physical Damage', type: 9, values: [['161-241', 1]] },
				{ displayMode: 0, name: 'Elemental Damage', type: 10, values: [['92-187', 4]] },
				{ displayMode: 0, name: 'Critical Strike Chance', type: 12, values: [['5.00%', 0]] },
				{ displayMode: 0, name: 'Attacks per Second', type: 13, values: [['1.47', 1]] },
				{ displayMode: 3, name: 'Weapon Range: {0} metres', type: 14, values: [['1.3', 0]] },
			],
			rarity: 'Rare',
			requirements: [
				{ displayMode: 0, name: 'Level', suffix: '(gem)', type: 62, values: [['66', 0]] },
				{ displayMode: 1, name: 'Str', type: 63, values: [['164', 0]] },
				{ displayMode: 1, name: 'Int', suffix: '(gem)', type: 65, values: [['46', 0]] },
			],
			socketedItems: [
				{
					additionalProperties: [
						{
							displayMode: 2,
							name: 'Experience',
							progress: 0.02,
							type: 20,
							values: [['557247/26083825', 0]],
						},
					],
					baseType: 'Ancestral Warchief',
					colour: 'S',
					descrText:
						'Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.',
					explicitMods: [
						'Totem lasts 12 seconds',
						'Summons a Totem which uses this Skill',
						'16% more Melee Damage while Totem is Active',
						'50% increased Totem Placement speed',
						'+1 metre to Melee Strike Range',
					],
					frameType: 4,
					h: 1,
					icon: 'https://web.poecdn.com/gen/image/WzMwLDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TbGFtVG90ZW1HZW0iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/dedff7f542/SlamTotemGem.png',
					id: '9b166da5b9d7b84be5a2b23f5b6e397672923634e3322a5c2382269d418c93b1',
					identified: true,
					ilvl: 0,
					league: 'Hardcore Necropolis',
					name: '',
					properties: [
						{ displayMode: 0, name: 'Attack, Totem, AoE, Slam, Melee', values: [] },
						{ displayMode: 0, name: 'Level', type: 5, values: [['17', 0]] },
						{ displayMode: 0, name: 'Cost', values: [['10 Mana', 0]] },
						{ displayMode: 0, name: 'Attack Speed', values: [['90% of base', 0]] },
						{ displayMode: 0, name: 'Attack Damage', values: [['157.2% of base', 0]] },
						{ displayMode: 0, name: 'Effectiveness of Added Damage', values: [['157%', 0]] },
					],
					requirements: [
						{ displayMode: 0, name: 'Level', type: 62, values: [['64', 0]] },
						{ displayMode: 1, name: 'Str', type: 63, values: [['142', 0]] },
					],
					secDescrText:
						"Summons an Ancestor Totem which attacks enemies with a powerful slam while you're near it. Being near it grants you more melee damage. Requires a Melee Weapon or Unarmed.",
					socket: 0,
					support: false,
					typeLine: 'Ancestral Warchief',
					verified: false,
					w: 1,
				},
				{
					additionalProperties: [
						{
							displayMode: 2,
							name: 'Experience',
							progress: 0.47,
							type: 20,
							values: [['7660059/16159983', 0]],
						},
					],
					baseType: 'Multiple Totems Support',
					colour: 'S',
					descrText:
						'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
					explicitMods: [
						'Supported Skills have +2 to maximum number of Summoned Totems',
						'Supported Skills Summon two Totems instead of one',
						'Supported Skills deal 25% less Damage',
					],
					frameType: 4,
					h: 1,
					icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L011bHRpcGxlVG90ZW1zIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/dc8f032f0b/MultipleTotems.png',
					id: 'ceeb8324d6654eee3157cf4eb0563f2409b290765c5fbe6c7ac032089f9c402e',
					identified: true,
					ilvl: 0,
					league: 'Hardcore Necropolis',
					name: '',
					properties: [
						{ displayMode: 0, name: 'Totem, Support', values: [] },
						{ displayMode: 0, name: 'Level', type: 5, values: [['16', 0]] },
						{ displayMode: 0, name: 'Cost & Reservation Multiplier', values: [['140%', 0]] },
					],
					requirements: [
						{ displayMode: 0, name: 'Level', type: 62, values: [['66', 0]] },
						{ displayMode: 1, name: 'Str', type: 63, values: [['66', 0]] },
						{ displayMode: 1, name: 'Int', type: 65, values: [['46', 0]] },
					],
					secDescrText: 'Supports skills which summon totems.',
					socket: 1,
					support: true,
					typeLine: 'Multiple Totems Support',
					verified: false,
					w: 1,
				},
				{
					additionalProperties: [
						{
							displayMode: 2,
							name: 'Experience',
							progress: 0.23,
							type: 20,
							values: [['6940577/29817117', 0]],
						},
					],
					baseType: 'Intimidating Cry',
					colour: 'S',
					descrText:
						'Place into an item socket of the right colour to gain this skill. Right click to remove from a socket.',
					explicitMods: [
						'Base duration is 4.80 seconds',
						'32% increased Warcry Speed',
						'Enemies Taunted by this Warcry are Intimidated',
						'Counts total Power of Enemies in Range',
						'Buff causes your Hits to Overwhelm 5% Physical Damage Reduction per 5 Power, up to 30%',
						'Exerts the next 2 Melee Attacks you perform',
						'Exerted Attacks deal Double Damage',
					],
					frameType: 4,
					h: 1,
					icon: 'https://web.poecdn.com/gen/image/WzMwLDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9JbnRpbWlkYXRpbmdDcnkiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/4a29f84dd1/IntimidatingCry.png',
					id: '89d14b9c33238c2d1d8a86ab40ae96f1d726be821e46269402653d0f7d2f892e',
					identified: true,
					ilvl: 0,
					league: 'Hardcore Necropolis',
					name: '',
					properties: [
						{ displayMode: 0, name: 'Warcry, AoE, Duration, Physical', values: [] },
						{ displayMode: 0, name: 'Level', type: 5, values: [['17', 0]] },
						{ displayMode: 0, name: 'Cost', values: [['18 Mana', 0]] },
						{ displayMode: 0, name: 'Cooldown Time', values: [['8.00 sec', 0]] },
						{ displayMode: 0, name: 'Use Time', values: [['0.80 sec', 0]] },
					],
					requirements: [
						{ displayMode: 0, name: 'Level', type: 62, values: [['63', 0]] },
						{ displayMode: 1, name: 'Str', type: 63, values: [['140', 0]] },
					],
					secDescrText:
						'Performs a warcry, taunting nearby enemies to attack the user and exerting subsequent attacks. Grants a buff which lowers the effect of enemy physical damage reduction against your hits.',
					socket: 2,
					support: false,
					typeLine: 'Intimidating Cry',
					verified: false,
					w: 1,
				},
				{
					additionalProperties: [
						{
							displayMode: 2,
							name: 'Experience',
							progress: 0.13,
							type: 20,
							values: [['3316530/26260555', 0]],
						},
					],
					baseType: 'Melee Physical Damage Support',
					colour: 'S',
					descrText:
						'This is a Support Gem. It does not grant a bonus to your character, but to skills in sockets connected to it. Place into an item socket connected to a socket containing the Skill Gem you wish to augment. Right click to remove from a socket.',
					explicitMods: [
						'Supported Skills deal 46% more Melee Physical Damage',
						'Supported Skills deal 46% more Damage with Bleeding and Poison caused by Melee Hits',
						'Supported Skills have 10% less Attack Speed',
					],
					frameType: 4,
					h: 1,
					icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvR2Vtcy9TdXBwb3J0L0luY3JlYXNlZFBoeXNpY2FsRGFtYWdlIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/99e02beaac/IncreasedPhysicalDamage.png',
					id: 'd4e8fe3d548dc2be0e28062704607743f732a08d031475260e35e7ee8bd933d7',
					identified: true,
					ilvl: 0,
					league: 'Hardcore Necropolis',
					name: '',
					properties: [
						{ displayMode: 0, name: 'Melee, Physical, Support, Attack', values: [] },
						{ displayMode: 0, name: 'Level', type: 5, values: [['17', 0]] },
						{ displayMode: 0, name: 'Cost & Reservation Multiplier', values: [['130%', 0]] },
					],
					requirements: [
						{ displayMode: 0, name: 'Level', type: 62, values: [['64', 0]] },
						{ displayMode: 1, name: 'Str', type: 63, values: [['102', 0]] },
					],
					secDescrText: 'Supports melee attack skills.',
					socket: 3,
					support: true,
					typeLine: 'Melee Physical Damage Support',
					verified: false,
					w: 1,
				},
			],
			sockets: [
				{ attr: 'S', group: 0, sColour: 'R' },
				{ attr: 'S', group: 0, sColour: 'R' },
				{ attr: 'S', group: 0, sColour: 'R' },
				{ attr: 'S', group: 0, sColour: 'R' },
			],
			typeLine: 'Plated Maul',
			verified: false,
			w: 2,
			x: 10,
			y: 0,
		},
	],
	metadata: { colour: 'f0ff80' },
	name: 'a',
	type: 'PremiumStash',
} as TabWithItems;
