import { TabWithItems } from '../../poe.types.js';
export const blight: TabWithItems = {
	id: 'a7e78f8a20',
	index: 91,
	items: [
		{
			baseType: 'Teal Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9UZWFsT2lsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/b6712a15cf/TealOil.png',
			id: '9a3250b89ae2538c9573b023a792004ba7066ac5e501b4d2666695f91127fb29',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['113/10', 0]] }],
			stackSize: 113,
			typeLine: 'Teal Oil',
			verified: false,
			w: 1,
			x: 4,
			y: 0,
		},
		{
			baseType: 'Indigo Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9JbmRpZ29PaWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/f9356f7cb0/IndigoOil.png',
			id: 'ba339348112cc7b7670b40517614d82918ad540aa59c210271bf7364f43a335e',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['37/10', 0]] }],
			stackSize: 37,
			typeLine: 'Indigo Oil',
			verified: false,
			w: 1,
			x: 6,
			y: 0,
		},
		{
			baseType: 'Azure Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9BenVyZU9pbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/926343421b/AzureOil.png',
			id: '62bf3b96d0ec4003c127da6a619cd68598ad16841fd48af882f50488b2953636',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['36/10', 0]] }],
			stackSize: 36,
			typeLine: 'Azure Oil',
			verified: false,
			w: 1,
			x: 5,
			y: 0,
		},
		{
			baseType: 'Violet Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9WaW9sZXRPaWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/64c679a735/VioletOil.png',
			id: '78dc8b99ca5aa45a2c363e8b1048091d88b290248f09dbdc3abdce6154f9ef18',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['28/10', 0]] }],
			stackSize: 28,
			typeLine: 'Violet Oil',
			verified: false,
			w: 1,
			x: 7,
			y: 0,
		},
		{
			baseType: 'Black Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9CbGFja09pbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/763ed79fad/BlackOil.png',
			id: '5eddea591c1bcb6d42046750d5a8bc86676200103feb09cd47377c7aef5574d1',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['16/10', 0]] }],
			stackSize: 16,
			typeLine: 'Black Oil',
			verified: false,
			w: 1,
			x: 9,
			y: 0,
		},
		{
			baseType: 'Crimson Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9Dcmltc29uT2lsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/54fb620c7e/CrimsonOil.png',
			id: 'ea5c267045efc1218e68bf4dd4e5e5d1192e491d93db0d36f6b90160019e7f8a',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['13/10', 0]] }],
			stackSize: 13,
			typeLine: 'Crimson Oil',
			verified: false,
			w: 1,
			x: 8,
			y: 0,
		},
		{
			baseType: 'Sepia Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9TZXBpYU9pbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/580407bed5/SepiaOil.png',
			id: '4b2dad4337163967b77469793ccfbdd73f4c6f1dd2f6c5d8173731d77c44896d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['10/10', 0]] }],
			stackSize: 10,
			typeLine: 'Sepia Oil',
			verified: false,
			w: 1,
			x: 1,
			y: 0,
		},
		{
			baseType: 'Amber Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9BbWJlck9pbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/931f4d2fdd/AmberOil.png',
			id: 'b6dbaed01648153ca1610e2dd015bd3d5710b3dc1a94fe592b3ab8abf6f67f9b',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['6/10', 0]] }],
			stackSize: 6,
			typeLine: 'Amber Oil',
			verified: false,
			w: 1,
			x: 2,
			y: 0,
		},
		{
			baseType: 'Verdant Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9WZXJkYW50T2lsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/55a911a67d/VerdantOil.png',
			id: '1cd9a141e8585e56bd0b2ceebb7da9ba36ca03105f3dd5c2eba0730b0cd2b20d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['6/10', 0]] }],
			stackSize: 6,
			typeLine: 'Verdant Oil',
			verified: false,
			w: 1,
			x: 3,
			y: 0,
		},
		{
			baseType: 'Silver Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9TaWx2ZXJPaWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/fb57de2d95/SilverOil.png',
			id: '223e26fea3dc45e0554004ae54569ec82905c6734b8428305d895deaff564a0a',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/10', 0]] }],
			stackSize: 4,
			typeLine: 'Silver Oil',
			verified: false,
			w: 1,
			x: 11,
			y: 0,
		},
		{
			baseType: 'Opalescent Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9PcGFsZXNjZW50T2lsIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/11d5d92171/OpalescentOil.png',
			id: '8f283b08500e6d6048709e0cb54d11db647a6f92480b6bb5b943bc870861fb6d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/10', 0]] }],
			stackSize: 2,
			typeLine: 'Opalescent Oil',
			verified: false,
			w: 1,
			x: 10,
			y: 0,
		},
		{
			baseType: 'Clear Oil',
			descrText:
				'Can be combined with other Oils at Cassia to Enchant Rings or Amulets, or to modify Blighted Maps.',
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvT2lscy9DbGVhck9pbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/de298bd226/ClearOil.png',
			id: 'ef190b09cf93807ba19cc9dd9e78854c231c04c216333748cbcdc79e006e6f31',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/10', 0]] }],
			stackSize: 2,
			typeLine: 'Clear Oil',
			verified: false,
			w: 1,
			x: 0,
			y: 0,
		},
		{
			baseType: 'Blighted Vault Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9WYXVsdCIsInciOjEsImgiOjEsInNjYWxlIjoxLCJtbiI6OSwibXQiOjE1LCJtYiI6dHJ1ZX1d/2dd4aa85aa/Vault.png',
			id: 'd4c89c222cb230854a0ad3080db5bf3c917fd558a135b00eb32e9d4fc055ab90',
			identified: true,
			ilvl: 83,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['15', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Vault Map',
			verified: false,
			w: 1,
			x: 20,
			y: 0,
		},
		{
			baseType: 'Blighted Summit Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9TdW1taXQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNiwibWIiOnRydWV9XQ/24904e0a5b/Summit.png',
			id: 'c2124e3306dd26a40c4e092aa2165fcbb3ce35b6345a9d8348a392a3cfd4210a',
			identified: true,
			ilvl: 83,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['16', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Summit Map',
			verified: false,
			w: 1,
			x: 27,
			y: 0,
		},
		{
			baseType: 'Blighted Palace Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9QYWxhY2UiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNSwibWIiOnRydWV9XQ/83b2f54808/Palace.png',
			id: '7d654bc156a7b486d83a9885e6aca9caf0b5ec3c64dfbb42ccdd646fcef980f9',
			identified: true,
			ilvl: 82,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['15', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Palace Map',
			verified: false,
			w: 1,
			x: 19,
			y: 0,
		},
		{
			baseType: 'Blighted Peninsula Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9EcnlQZW5pbnN1bGEiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNCwibWIiOnRydWV9XQ/cee1e12e47/DryPeninsula.png',
			id: 'ef060852531f7072d6f3eb2c28e5c3619515241b35e019d0c413c99420410a21',
			identified: true,
			ilvl: 84,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['14', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Peninsula Map',
			verified: false,
			w: 1,
			x: 21,
			y: 0,
		},
		{
			baseType: 'Blighted Arcade Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9BcmNhZGUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxMywibWIiOnRydWV9XQ/01658f1de1/Arcade.png',
			id: 'fc21ac8cc5e1ed7cf23484e3b951df568af5b2c768d29e96ea0d84c3790f14bb',
			identified: true,
			ilvl: 81,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['13', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Arcade Map',
			verified: false,
			w: 1,
			x: 22,
			y: 0,
		},
		{
			baseType: 'Blighted Sulphur Vents Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9Db3Jyb3Npb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNCwibWIiOnRydWV9XQ/40a9e6d5e0/Corrosion.png',
			id: '1f40a42a5ee8c4636ababe40f2ea46baef82d881ca0d40e06700dbb862b9ecc7',
			identified: true,
			ilvl: 81,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['14', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Sulphur Vents Map',
			verified: false,
			w: 1,
			x: 18,
			y: 0,
		},
		{
			baseType: 'Blighted Ashen Wood Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9EcnlXb29kcyIsInciOjEsImgiOjEsInNjYWxlIjoxLCJtbiI6OSwibXQiOjE1LCJtYiI6dHJ1ZX1d/8ee79831f3/DryWoods.png',
			id: 'ec88150223017896f56b4276bd1ca3ea371f9876c4ee0df0e9bc38c8908e42a4',
			identified: true,
			ilvl: 82,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['15', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Ashen Wood Map',
			verified: false,
			w: 1,
			x: 23,
			y: 0,
		},
		{
			baseType: 'Blighted Arcade Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9BcmNhZGUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxMywibWIiOnRydWV9XQ/01658f1de1/Arcade.png',
			id: 'ee4e55075bca4bde857110ee06a1bf9af810d6e61aded74fe631804dd273714a',
			identified: true,
			ilvl: 82,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['13', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Arcade Map',
			verified: false,
			w: 1,
			x: 26,
			y: 0,
		},
		{
			baseType: 'Blighted Promenade Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9Qcm9tZW5hZGUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNSwibWIiOnRydWV9XQ/96e4b92e8d/Promenade.png',
			id: '9ef3887fa32158d1cad8817834ee3ba06628f557b390e140a9f4f1e91c53ffa4',
			identified: true,
			ilvl: 83,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [{ displayMode: 0, name: 'Map Tier', type: 1, values: [['15', 0]] }],
			rarity: 'Normal',
			typeLine: 'Blighted Promenade Map',
			verified: false,
			w: 1,
			x: 24,
			y: 0,
		},
		{
			baseType: 'Blighted Sulphur Vents Map',
			descrText: 'Travel to this Map by using it in a personal Map Device. Maps can only be used once.',
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI4LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9BdGxhczJNYXBzL05ldy9Db3Jyb3Npb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MSwibW4iOjksIm10IjoxNCwibWIiOnRydWV9XQ/40a9e6d5e0/Corrosion.png',
			id: 'a191550061c42d6076c8cbe220c03630162dd93dd773dd7960b8b0969ba787cb',
			identified: true,
			ilvl: 83,
			implicitMods: [
				"Area is infested with Fungal Growths\nMap's Item Quantity Modifiers also affect Blight Chest count at 25% value\nCan be Anointed up to 3 times",
				'Natural inhabitants of this area have been removed',
			],
			inventoryId: 'Stash1',
			league: 'Standard',
			name: '',
			properties: [
				{ displayMode: 0, name: 'Map Tier', type: 1, values: [['14', 0]] },
				{ displayMode: 0, name: 'Item Quantity', type: 2, values: [['+8%', 1]] },
				{ displayMode: 0, name: 'Quality', type: 6, values: [['+8%', 1]] },
			],
			rarity: 'Normal',
			typeLine: 'Superior Blighted Sulphur Vents Map',
			verified: false,
			w: 1,
			x: 25,
			y: 0,
		},
	],
	metadata: { colour: 'ffd500' },
	name: 'Oil (Remove-only)',
	type: 'BlightStash',
} satisfies TabWithItems;
