import { TabWithItems } from '../../poe.types.js';

export const essence: TabWithItems = {
	id: '8f493e641b',
	index: 12,
	items: [
		{
			baseType: 'Screaming Essence of Greed',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Weapon: (0.9-1.1)% of Physical Attack Damage Leeched as Life',
				'Body Armour: (90-99) to maximum Life',
				'Helmet: (80-89) to maximum Life',
				'Shield: (90-99) to maximum Life',
				'Other Armour: (70-79) to maximum Life',
				'Quiver: (0.9-1.1)% of Physical Attack Damage Leeched as Life',
				'Belt: (24-27)% increased Flask Life Recovery rate',
				'Other Jewellery: Regenerate (24.1-32) Life per second',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9HcmVlZDUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/cc96065240/Greed5.png',
			id: '3db8b292e0adb80e6614f08326b91cb63d25544361ac1ffc842489edaa324d70',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['7/9', 0]] }],
			stackSize: 7,
			typeLine: 'Screaming Essence of Greed',
			verified: false,
			w: 1,
			x: 18,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Fear',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Minions deal (50-66)% increased Damage',
				'Two Handed Weapon: Minions deal (85-106)% increased Damage',
				'Gloves: Minions deal (22-24)% increased Damage',
				'Helmet: (22-24)% increased Minion Accuracy Rating',
				'Other Armour: Minions have (22-24)% increased maximum Life',
				'Quiver: Minions have (22-24)% increased Movement Speed',
				'Belt: Minions have (22-24)% increased maximum Life',
				'Other Jewellery: Minions have (22-24)% increased Movement Speed',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9GZWFyNSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/1a0f1c6a68/Fear5.png',
			id: 'a8776f7674c41e7a16881c91572e46373e9356fdcd7e575d020bf88614e3120c',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['6/9', 0]] }],
			stackSize: 6,
			typeLine: 'Screaming Essence of Fear',
			verified: false,
			w: 1,
			x: 49,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Hatred',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Bow: Adds (57-77) to (114-132) Cold Damage',
				'Two Handed Melee Weapon: Adds (57-77) to (114-132) Cold Damage',
				'Other Weapon: Adds (31-42) to (62-71) Cold Damage',
				'Armour: (24-29)% to Cold Resistance',
				'Quiver: (24-29)% to Cold Resistance',
				'Belt: (24-29)% to Cold Resistance',
				'Other Jewellery: (19-22)% increased Cold Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9IYXRyZWQ0IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/2137aa1054/Hatred4.png',
			id: '38fb2b7f24a417576802310d3f3220535b5fcefdf9ba419c7ee0296fcfcb4eb7',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['5/9', 0]] }],
			stackSize: 5,
			typeLine: 'Wailing Essence of Hatred',
			verified: false,
			w: 1,
			x: 3,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Wrath',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Bow: Adds (11-14) to (208-242) Lightning Damage',
				'Two Handed Melee Weapon: Adds (11-14) to (208-242) Lightning Damage',
				'Other Weapon: Adds (5-8) to (112-131) Lightning Damage',
				'Armour: (24-29)% to Lightning Resistance',
				'Quiver: (24-29)% to Lightning Resistance',
				'Belt: (24-29)% to Lightning Resistance',
				'Other Jewellery: (13-17)% increased Lightning Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9XcmF0aDQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/117a0bef80/Wrath4.png',
			id: 'cdab8f4660fcfe7cac2735ff73c6cadf14fa0ded98a6a0cefee09614d8b2f237',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['5/9', 0]] }],
			stackSize: 5,
			typeLine: 'Wailing Essence of Wrath',
			verified: false,
			w: 1,
			x: 63,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Anger',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Bow: Adds (110-150) to (223-260) Fire Damage',
				'Two Handed Melee Weapon: Adds (110-150) to (223-260) Fire Damage',
				'Other Weapon: Adds (59-81) to (120-140) Fire Damage',
				'Armour: (36-41)% to Fire Resistance',
				'Quiver: (36-41)% to Fire Resistance',
				'Belt: (36-41)% to Fire Resistance',
				'Other Jewellery: (23-26)% increased Fire Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9BbmdlcjUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/19d11b6ceb/Anger5.png',
			id: '864cd31789ced6c96f3d945c7e975f5033670e2aba44c1c30b2131929f5e6f4a',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['5/9', 0]] }],
			stackSize: 5,
			typeLine: 'Screaming Essence of Anger',
			verified: false,
			w: 1,
			x: 37,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Contempt',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Adds (8-12) to (17-20) Physical Damage',
				'Two Handed Weapon: Adds (13-17) to (28-32) Physical Damage',
				'Gloves: Adds (3-5) to (7-8) Physical Damage to Attacks',
				'Other Armour: Reflects (25-50) Physical Damage to Melee Attackers',
				'Quiver: Adds (6-9) to (13-15) Physical Damage to Attacks',
				'Amulet: Adds (6-9) to (13-15) Physical Damage to Attacks',
				'Ring: Adds (5-7) to (11-12) Physical Damage to Attacks',
				'Belt: Reflects (25-50) Physical Damage to Melee Attackers',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db250ZW1wdDQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/81bb512694/Contempt4.png',
			id: '72db80def42451069c33ed2d4fe51b65167d8667a5d41fb7029bceeb46fb1205',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['5/9', 0]] }],
			stackSize: 5,
			typeLine: 'Wailing Essence of Contempt',
			verified: false,
			w: 1,
			x: 24,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Dread',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Wand: (34-41)% increased Projectile Speed',
				'Bow: +1 to Level of Socketed Bow Gems',
				'Other One Handed Weapon: (12-16)% increased Impale Effect',
				'Two Handed Melee Weapon: (25-29)% increased Impale Effect',
				'Body Armour: (151-200) to Armour',
				'Helmet: (121-140) to Armour',
				'Shield: (151-225) to Armour',
				'Other Armour: (91-105) to Armour',
				'Quiver: (34-41)% increased Projectile Speed',
				'Amulet: (24-28)% increased Armour',
				'Ring: (80-120) to Armour',
				'Belt: (323-400) to Armour',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9EcmVhZDUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/da89306159/Dread5.png',
			id: '4dc84614e7fa2f4f32f40728ba0e52c5c7173657a6755751c9cbec7051847274',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['5/9', 0]] }],
			stackSize: 5,
			typeLine: 'Screaming Essence of Dread',
			verified: false,
			w: 1,
			x: 91,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Sorrow',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Damage Penetrates 5% Cold Resistance',
				'Two Handed Weapon: Damage Penetrates (9-10)% Cold Resistance',
				'Other Item: (28-32) to Dexterity',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Tb3Jyb3c0IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/f755c252fc/Sorrow4.png',
			id: 'ba0d5104006fb7cbc6f554ccf910a6fa1e10aa82294474823318df28ead151d6',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Wailing Essence of Sorrow',
			verified: false,
			w: 1,
			x: 30,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Torment',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Adds (2-9) to (109-115) Lightning Damage to Spells',
				'Two Handed Weapon: Adds (5-12) to (164-173) Lightning Damage to Spells',
				'Gloves: Adds (1-2) to (27-28) Lightning Damage to Attacks',
				'Body Armour: (7-8)% chance to Avoid Lightning Damage from Hits',
				'Shield: (7-8)% chance to Avoid Lightning Damage from Hits',
				'Other Armour: (47-50)% chance to Avoid being Shocked',
				'Quiver: Adds (3-8) to (89-99) Lightning Damage to Attacks',
				'Belt: (47-50)% chance to Avoid being Shocked',
				'Other Jewellery: Adds (3-6) to (57-61) Lightning Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Ub3JtZW50NSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/5a7f95ea8d/Torment5.png',
			id: '3216a4446e62e7ecf85865c371c87850edd72c5887272e9e5a41e2742b27750e',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Screaming Essence of Torment',
			verified: false,
			w: 1,
			x: 43,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Woe',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: (40-54)% increased Spell Damage',
				'Two Handed Weapon: (60-84)% increased Spell Damage',
				'Gloves: (18-26) to maximum Energy Shield',
				'Boots: (18-26) to maximum Energy Shield',
				'Shield: (39-49) to maximum Energy Shield',
				'Other Armour: (31-38) to maximum Energy Shield',
				'Quiver: (26-30)% increased Damage with Bow Skills',
				'Amulet: (11-13)% increased maximum Energy Shield',
				'Ring: (23-26) to maximum Energy Shield',
				'Belt: (23-26) to maximum Energy Shield',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Xb2U0IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/989ddf8de2/Woe4.png',
			id: '3c5887f6a2dd0a157a4b73d0ced8e72c6acafc6d4a178938be43ca1bd732c663',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Wailing Essence of Woe',
			verified: false,
			w: 1,
			x: 10,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Hatred',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Bow: Adds (99-136) to (200-232) Cold Damage',
				'Two Handed Melee Weapon: Adds (99-136) to (200-232) Cold Damage',
				'Other Weapon: Adds (54-74) to (108-126) Cold Damage',
				'Armour: (36-41)% to Cold Resistance',
				'Quiver: (36-41)% to Cold Resistance',
				'Belt: (36-41)% to Cold Resistance',
				'Other Jewellery: (23-26)% increased Cold Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9IYXRyZWQ1IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/6ce21e2462/Hatred5.png',
			id: '2be854c98400d84defae8451c938d852799b51db4684527ba1c3f82044b4269a',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Screaming Essence of Hatred',
			verified: false,
			w: 1,
			x: 4,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Rage',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Damage Penetrates 6% Fire Resistance',
				'Two Handed Weapon: Damage Penetrates (11-12)% Fire Resistance',
				'Other Item: (33-37) to Strength',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9SYWdlNSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/89c03ab737/Rage5.png',
			id: '0727e4f68daba9d6b2d06db114eff893a8e32e543a8cd7fa999d9fd3e75273cb',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Screaming Essence of Rage',
			verified: false,
			w: 1,
			x: 59,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Scorn',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Weapon: (80-99)% increased Critical Strike Chance for Spells',
				'Body Armour: (31-39)% increased Stun Threshold',
				'Shield: (80-99)% increased Critical Strike Chance for Spells',
				'Other Armour: (23-26)% chance to Avoid being Stunned',
				'Quiver: (25-29)% to Global Critical Strike Multiplier',
				'Amulet: (25-29)% to Global Critical Strike Multiplier',
				'Ring: (15-17)% to Global Critical Strike Multiplier',
				'Belt: (12-13)% reduced Enemy Stun Threshold',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TY29ybjUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/9031bf8c8e/Scorn5.png',
			id: '0a6def34c0a3efd2fe06700228c36cac0db7ef34baf22f1ba3c80d2452e55afb',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Screaming Essence of Scorn',
			verified: false,
			w: 1,
			x: 94,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Fear',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Minions deal (40-54)% increased Damage',
				'Two Handed Weapon: Minions deal (60-84)% increased Damage',
				'Gloves: Minions deal (19-21)% increased Damage',
				'Helmet: (19-21)% increased Minion Accuracy Rating',
				'Other Armour: Minions have (19-21)% increased maximum Life',
				'Quiver: Minions have (19-21)% increased Movement Speed',
				'Belt: Minions have (19-21)% increased maximum Life',
				'Other Jewellery: Minions have (19-21)% increased Movement Speed',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9GZWFyNCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/9f6bef7be1/Fear4.png',
			id: 'a72468aea3e8b4c4e3a878566f9a82aea227d6ee06cb43402868b9dbea49bf9a',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Wailing Essence of Fear',
			verified: false,
			w: 1,
			x: 48,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Spite',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Damage Penetrates 5% Lightning Resistance',
				'Two Handed Weapon: Damage Penetrates (9-10)% Lightning Resistance',
				'Other Item: (28-32) to Intelligence',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TcGl0ZTQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/d47263973c/Spite4.png',
			id: '5d0934abe67c16b1de2dfbb5f318a761f75283505a5d017dfb02d9e09266f149',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Wailing Essence of Spite',
			verified: false,
			w: 1,
			x: 80,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Woe',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'One Handed Weapon: (30-39)% increased Spell Damage',
				'Two Handed Weapon: (45-59)% increased Spell Damage',
				'Armour: (17-23) to maximum Energy Shield',
				'Quiver: (21-25)% increased Damage with Bow Skills',
				'Amulet: (8-10)% increased maximum Energy Shield',
				'Ring: (16-19) to maximum Energy Shield',
				'Belt: (16-19) to maximum Energy Shield',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Xb2UzIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/4bce548a80/Woe3.png',
			id: 'fc52fa185d9e3086f1f67b83c3aa1613edfb803d5c9d4ce75cc1e994b0efeb06',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Weeping Essence of Woe',
			verified: false,
			w: 1,
			x: 9,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Anguish',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Adds (31-42) to (64-73) Fire Damage to Spells',
				'Two Handed Weapon: Adds (42-56) to (85-99) Fire Damage to Spells',
				'Gloves: Adds (7-10) to (15-18) Fire Damage to Attacks',
				'Body Armour: (7-8)% chance to Avoid Fire Damage from Hits',
				'Shield: (7-8)% chance to Avoid Fire Damage from Hits',
				'Other Armour: (47-50)% chance to Avoid being Ignited',
				'Quiver: Adds (27-35) to (53-62) Fire Damage to Attacks',
				'Belt: (47-50)% chance to Avoid being Ignited',
				'Other Jewellery: Adds (16-22) to (32-38) Fire Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Bbmd1aXNoNSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/3a010ed0e8/Anguish5.png',
			id: '49659fbee054605b46348b829840401bb11b7aab18cd49d1e86f0c68ab044938',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['4/9', 0]] }],
			stackSize: 4,
			typeLine: 'Screaming Essence of Anguish',
			verified: false,
			w: 1,
			x: 73,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Greed',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Weapon: (0.8-1)% of Physical Attack Damage Leeched as Life',
				'Gloves: (60-69) to maximum Life',
				'Boots: (60-69) to maximum Life',
				'Other Armour: (70-79) to maximum Life',
				'Quiver: (0.8-1)% of Physical Attack Damage Leeched as Life',
				'Belt: (20-23)% increased Flask Life Recovery rate',
				'Other Jewellery: Regenerate (16.1-24) Life per second',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9HcmVlZDQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/4b55a2c50f/Greed4.png',
			id: 'd0d0c5a13fc3303576ddd3b5ac6527befc3b11d4c0d2beeb0f71352e0de42c7d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Wailing Essence of Greed',
			verified: false,
			w: 1,
			x: 17,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Zeal',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Melee Weapon: (20-22)% increased Attack Speed',
				'Ranged Weapon: (11-12)% increased Attack Speed',
				'Gloves: (8-10)% increased Attack Speed',
				'Boots: 20% increased Movement Speed',
				'Body Armour: (21-25)% increased Totem Placement speed',
				'Helmet: (15-20)% increased Warcry Speed',
				'Other Armour: (20-22)% increased Stun and Block Recovery',
				'Quiver: (6-7)% increased Attack Speed',
				'Amulet: (5-8)% increased Cast Speed',
				'Ring: (5-8)% increased Cast Speed',
				'Belt: (7-10)% increased Trap and Mine Throwing Speed',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9aZWFsNCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/36f5f9a73f/Zeal4.png',
			id: '3b48202e604728a430d8512692f3ddf9832ccef99c971830c48ff5163e4c7063',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Wailing Essence of Zeal',
			verified: false,
			w: 1,
			x: 84,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Sorrow',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'One Handed Weapon: Damage Penetrates 4% Cold Resistance',
				'Two Handed Weapon: Damage Penetrates (7-8)% Cold Resistance',
				'Other Item: (18-22) to Dexterity',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Tb3Jyb3czIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/577fda6e69/Sorrow3.png',
			id: '0a892e5338d632d7d8e55a07f856e49accaa26e56334b5f61d1bd40cf9372e6e',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Weeping Essence of Sorrow',
			verified: false,
			w: 1,
			x: 29,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Contempt',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Adds (13-18) to (27-31) Physical Damage',
				'Two Handed Weapon: Adds (20-28) to (43-51) Physical Damage',
				'Gloves: Adds (4-5) to (8-9) Physical Damage to Attacks',
				'Other Armour: Reflects (51-100) Physical Damage to Melee Attackers',
				'Quiver: Adds (9-12) to (19-22) Physical Damage to Attacks',
				'Amulet: Adds (9-12) to (19-22) Physical Damage to Attacks',
				'Ring: Adds (6-8) to (12-13) Physical Damage to Attacks',
				'Belt: Reflects (51-100) Physical Damage to Melee Attackers',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db250ZW1wdDUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/473f05aaee/Contempt5.png',
			id: '80393ec7cc6490ac80e8ec3de7c5a95a66cf24937bb3d4bc0f1152bcf7379a71',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Screaming Essence of Contempt',
			verified: false,
			w: 1,
			x: 25,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Doubt',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Weapon: (326-455) to Accuracy Rating',
				'Body Armour: (151-200) to Evasion Rating',
				'Helmet: (121-140) to Evasion Rating',
				'Shield: (151-225) to Evasion Rating',
				'Other Armour: (91-105) to Evasion Rating',
				'Quiver: (251-350) to Accuracy Rating',
				'Amulet: (24-28)% increased Evasion Rating',
				'Other Jewellery: (81-120) to Evasion Rating',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Eb3VidDUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/203952b786/Doubt5.png',
			id: 'b3de1fbd8667a2a35a5e9c320edd9c6b16ec4a9d8b63cb00636e2065fb5ad52b',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Screaming Essence of Doubt',
			verified: false,
			w: 1,
			x: 69,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Torment',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Adds (2-7) to (84-88) Lightning Damage to Spells',
				'Two Handed Weapon: Adds (3-10) to (126-133) Lightning Damage to Spells',
				'Gloves: Adds (1-2) to (22-23) Lightning Damage to Attacks',
				'Body Armour: (6-7)% chance to Avoid Lightning Damage from Hits',
				'Shield: (6-7)% chance to Avoid Lightning Damage from Hits',
				'Other Armour: (43-46)% chance to Avoid being Shocked',
				'Quiver: Adds (2-5) to (56-62) Lightning Damage to Attacks',
				'Belt: (43-46)% chance to Avoid being Shocked',
				'Other Jewellery: Adds (1-4) to (40-43) Lightning Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Ub3JtZW50NCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/59e31a8f9b/Torment4.png',
			id: 'ebdcb9c768c19615e4b83237443a8b77debf3b0c9d7b837f62ea2c03e51917c3',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Wailing Essence of Torment',
			verified: false,
			w: 1,
			x: 42,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Contempt',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'One Handed Weapon: Adds (6-9) to (13-15) Physical Damage',
				'Two Handed Weapon: Adds (10-13) to (21-25) Physical Damage',
				'Gloves: Adds (3-4) to (6-7) Physical Damage to Attacks',
				'Other Armour: Reflects (11-24) Physical Damage to Melee Attackers',
				'Quiver: Adds (4-6) to (9-10) Physical Damage to Attacks',
				'Belt: Reflects (11-24) Physical Damage to Melee Attackers',
				'Other Jewellery: Adds (4-6) to (9-10) Physical Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Db250ZW1wdDMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/7347bf5d1c/Contempt3.png',
			id: 'e00e3097b1bf52f04b9ce3ebe9893f18fb4aad5df4f8e2c4bbe1df48ae6d3864',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Weeping Essence of Contempt',
			verified: false,
			w: 1,
			x: 23,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Suffering',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Adds (26-35) to (51-60) Cold Damage to Spells',
				'Two Handed Weapon: Adds (39-52) to (77-90) Cold Damage to Spells',
				'Gloves: Adds (6-9) to (13-16) Cold Damage to Attacks',
				'Body Armour: (7-8)% chance to Avoid Cold Damage from Hits',
				'Shield: (7-8)% chance to Avoid Cold Damage from Hits',
				'Other Armour: (47-50)% chance to Avoid being Frozen',
				'Quiver: Adds (18-24) to (36-42) Cold Damage to Attacks',
				'Belt: (47-50)% chance to Avoid being Frozen',
				'Other Jewellery: Adds (12-16) to (24-28) Cold Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TdWZmZXJpbmc1IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/061b600839/Suffering5.png',
			id: 'fd27822ad723686d60f278c155b08caaf6a1a798179cc908732f9604bf49377b',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['3/9', 0]] }],
			stackSize: 3,
			typeLine: 'Screaming Essence of Suffering',
			verified: false,
			w: 1,
			x: 54,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Envy',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Adds (37-59) to (79-103) Chaos Damage',
				'Two Handed Weapon: Adds (61-103) to (149-193) Chaos Damage',
				'Armour: (21-25)% to Chaos Resistance',
				'Quiver: Adds (11-15) to (27-33) Chaos Damage to Attacks',
				'Belt: (21-25)% to Chaos Resistance',
				'Other Jewellery: (23-26)% increased Chaos Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9FbnZ5NSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/633982e75d/Envy5.png',
			id: '490995995d231c72798eee00436f4ede55a0549a6b395cc8eb703a30775722c5',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Screaming Essence of Envy',
			verified: false,
			w: 1,
			x: 97,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Loathing',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Weapon: (25-29)% increased Critical Strike Chance',
				'Gloves: (18-20)% increased Global Critical Strike Chance',
				'Boots: (21-25)% chance to Avoid Elemental Ailments',
				'Shield: (8-9)% Chance to Block',
				'Other Armour: (5-6)% increased Mana Reservation Efficiency of Skills',
				'Quiver: (30-34)% increased Global Critical Strike Chance',
				'Amulet: (30-34)% increased Global Critical Strike Chance',
				'Ring: (18-20)% increased Global Critical Strike Chance',
				'Belt: (26-30)% increased Stun Duration on Enemies',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Mb2F0aGluZzUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/367d456623/Loathing5.png',
			id: 'ee2c7c0037e3aa3f6d58d1fe21caf58717397434b172b6e20c52d290e62005c4',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Screaming Essence of Loathing',
			verified: false,
			w: 1,
			x: 77,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Wrath',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Bow: Adds (19-25) to (366-425) Lightning Damage',
				'Two Handed Melee Weapon: Adds (19-25) to (366-425) Lightning Damage',
				'Other Weapon: Adds (10-14) to (197-229) Lightning Damage',
				'Armour: (36-41)% to Lightning Resistance',
				'Quiver: (36-41)% to Lightning Resistance',
				'Belt: (36-41)% to Lightning Resistance',
				'Other Jewellery: (23-26)% increased Lightning Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9XcmF0aDUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/39bfab2d24/Wrath5.png',
			id: '59b9024da4d7636a5b7b5583a0ff1cc4176a151f31ec99238ba0a07086edbfd6',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Screaming Essence of Wrath',
			verified: false,
			w: 1,
			x: 64,
			y: 0,
		},
		{
			baseType: 'Remnant of Corruption',
			descrText:
				'Right click this item then left click a monster trapped by Essences to corrupt them. Corrupted Essences cannot be modified again.',
			explicitMods: ['Corrupts the Essences trapping a monster, modifying them unpredictably'],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Fc3NlbmNlQ29ycnVwdCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/0e84041aa5/EssenceCorrupt.png',
			id: 'b20caeb2d2532bd7cfeb574d2facfd171a2c94ad8c7923cdff92140bed5dd4dd',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Remnant of Corruption',
			verified: false,
			w: 1,
			x: 104,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Spite',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Damage Penetrates 6% Lightning Resistance',
				'Two Handed Weapon: Damage Penetrates (11-12)% Lightning Resistance',
				'Other Item: (33-37) to Intelligence',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TcGl0ZTUiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/76f8592685/Spite5.png',
			id: '924e151e0c1ccaf96c9b782b89c6e3436a4395038b9e26bb0b209f013eef4474',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Screaming Essence of Spite',
			verified: false,
			w: 1,
			x: 81,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Woe',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: (50-66)% increased Spell Damage',
				'Two Handed Weapon: (85-106)% increased Spell Damage',
				'Body Armour: (50-61) to maximum Energy Shield',
				'Helmet: (39-45) to maximum Energy Shield',
				'Shield: (50-59) to maximum Energy Shield',
				'Other Armour: (27-32) to maximum Energy Shield',
				'Quiver: (31-36)% increased Damage with Bow Skills',
				'Amulet: (14-16)% increased maximum Energy Shield',
				'Ring: (27-31) to maximum Energy Shield',
				'Belt: (27-31) to maximum Energy Shield',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Xb2U1IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/ec3cf669a0/Woe5.png',
			id: '046c245bbe4100a230223caaf70648896f153117ad8ee0c8f4e463ee32270582',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Screaming Essence of Woe',
			verified: false,
			w: 1,
			x: 11,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Fear',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'One Handed Weapon: Minions deal (30-39)% increased Damage',
				'Two Handed Weapon: Minions deal (45-59)% increased Damage',
				'Gloves: Minions deal (16-18)% increased Damage',
				'Helmet: (16-18)% increased Minion Accuracy Rating',
				'Other Armour: Minions have (16-18)% increased maximum Life',
				'Quiver: Minions have (16-18)% increased Movement Speed',
				'Belt: Minions have (16-18)% increased maximum Life',
				'Other Jewellery: Minions have (16-18)% increased Movement Speed',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9GZWFyMyIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/7d65a73894/Fear3.png',
			id: '93f9e3b6a28accd0181aee4bdc26bc755fb9113e8808d66ce3cf9e24510c3f2d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/9', 0]] }],
			stackSize: 2,
			typeLine: 'Weeping Essence of Fear',
			verified: false,
			w: 1,
			x: 47,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Doubt',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'Weapon: (131-215) to Accuracy Rating',
				'Armour: (64-82) to Evasion Rating',
				'Quiver: (100-165) to Accuracy Rating',
				'Amulet: (14-18)% increased Evasion Rating',
				'Other Jewellery: (36-60) to Evasion Rating',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Eb3VidDMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/d62cf232e7/Doubt3.png',
			id: 'a5704008149eadd2acee6cb612ae39112fcdd013e28a17b3c5743288d3f08aff',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Weeping Essence of Doubt',
			verified: false,
			w: 1,
			x: 67,
			y: 0,
		},
		{
			baseType: 'Weeping Essence of Hatred',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 60 and below',
				'',
				'Bow: Adds (29-40) to (58-68) Cold Damage',
				'Two Handed Melee Weapon: Adds (29-40) to (58-68) Cold Damage',
				'Other Weapon: Adds (16-21) to (31-37) Cold Damage',
				'Armour: (18-23)% to Cold Resistance',
				'Quiver: (18-23)% to Cold Resistance',
				'Belt: (18-23)% to Cold Resistance',
				'Other Jewellery: (15-18)% increased Cold Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9IYXRyZWQzIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/83a45f6ee9/Hatred3.png',
			id: '589afbba8fddd138e8a3d19323f13f408eea581b8f87e0b62ad6a75c2ee72390',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Weeping Essence of Hatred',
			verified: false,
			w: 1,
			x: 2,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Rage',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Damage Penetrates 5% Fire Resistance',
				'Two Handed Weapon: Damage Penetrates (9-10)% Fire Resistance',
				'Other Item: (28-32) to Strength',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9SYWdlNCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/94a3d5f6f2/Rage4.png',
			id: '656001628cd6afcfc8ad3c86f09bb49b85ad3c897bd001f37775afbec292ffa6',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Wailing Essence of Rage',
			verified: false,
			w: 1,
			x: 58,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Sorrow',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'One Handed Weapon: Damage Penetrates 6% Cold Resistance',
				'Two Handed Weapon: Damage Penetrates (11-12)% Cold Resistance',
				'Other Item: (33-37) to Dexterity',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Tb3Jyb3c1IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/34d568ff94/Sorrow5.png',
			id: 'afe10aa0561db0bf494b4c7706482556a05f67568b8740bc6070dca94ba25919',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Screaming Essence of Sorrow',
			verified: false,
			w: 1,
			x: 31,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Anger',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Bow: Adds (63-85) to (128-148) Fire Damage',
				'Two Handed Melee Weapon: Adds (63-85) to (128-148) Fire Damage',
				'Other Weapon: Adds (34-46) to (68-80) Fire Damage',
				'Armour: (24-29)% to Fire Resistance',
				'Quiver: (24-29)% to Fire Resistance',
				'Belt: (24-29)% to Fire Resistance',
				'Other Jewellery: (19-22)% increased Fire Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9BbmdlcjQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/2f3eca86d2/Anger4.png',
			id: '8fdbab23fb92bf09b0221f6976da09276cd31d496db75799936d17f84da94163',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Wailing Essence of Anger',
			verified: false,
			w: 1,
			x: 36,
			y: 0,
		},
		{
			baseType: 'Screaming Essence of Zeal',
			descrText: 'Right click this item then left click a normal or rare item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare or reforges a rare item, guaranteeing one property',
				'',
				'Melee Weapon: (23-25)% increased Attack Speed',
				'Ranged Weapon: (13-14)% increased Attack Speed',
				'Gloves: (11-13)% increased Attack Speed',
				'Boots: 25% increased Movement Speed',
				'Body Armour: (26-30)% increased Totem Placement speed',
				'Helmet: (21-25)% increased Warcry Speed',
				'Other Armour: (23-25)% increased Stun and Block Recovery',
				'Quiver: (8-9)% increased Attack Speed',
				'Amulet: (9-12)% increased Cast Speed',
				'Ring: (9-12)% increased Cast Speed',
				'Belt: (11-13)% increased Trap and Mine Throwing Speed',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9aZWFsNSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/f9189119bd/Zeal5.png',
			id: 'f374e9e3b7c36fab3237ddd19f3114ba7ae5c40a712a6818003b49c761122489',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Screaming Essence of Zeal',
			verified: false,
			w: 1,
			x: 85,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Suffering',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'One Handed Weapon: Adds (20-26) to (40-46) Cold Damage to Spells',
				'Two Handed Weapon: Adds (30-40) to (59-69) Cold Damage to Spells',
				'Gloves: Adds (5-7) to (10-12) Cold Damage to Attacks',
				'Body Armour: (6-7)% chance to Avoid Cold Damage from Hits',
				'Shield: (6-7)% chance to Avoid Cold Damage from Hits',
				'Other Armour: (43-46)% chance to Avoid being Frozen',
				'Quiver: Adds (15-20) to (30-35) Cold Damage to Attacks',
				'Belt: (43-46)% chance to Avoid being Frozen',
				'Other Jewellery: Adds (10-13) to (20-24) Cold Damage to Attacks',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9TdWZmZXJpbmc0IiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/b0edfe414b/Suffering4.png',
			id: 'af0c8f84f6735a051874f1a280471621f36bcd5a7dd2d1243e2bc0be0bcf08c6',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Wailing Essence of Suffering',
			verified: false,
			w: 1,
			x: 53,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Doubt',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Weapon: (216-325) to Accuracy Rating',
				'Gloves: (81-90) to Evasion Rating',
				'Boots: (81-90) to Evasion Rating',
				'Shield: (121-150) to Evasion Rating',
				'Other Armour: (102-120) to Evasion Rating',
				'Quiver: (166-250) to Accuracy Rating',
				'Amulet: (19-23)% increased Evasion Rating',
				'Other Jewellery: (61-80) to Evasion Rating',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Eb3VidDQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/d2f2f7c5d5/Doubt4.png',
			id: 'af649c445cb2fba6e063e2071e7495a7fc6402a71feed751090a4821efb1b568',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Wailing Essence of Doubt',
			verified: false,
			w: 1,
			x: 68,
			y: 0,
		},
		{
			baseType: 'Wailing Essence of Loathing',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 75 and below',
				'',
				'Weapon: (20-24)% increased Critical Strike Chance',
				'Gloves: (15-17)% increased Global Critical Strike Chance',
				'Boots: (16-20)% chance to Avoid Elemental Ailments',
				'Shield: (6-7)% Chance to Block',
				'Other Armour: (3-4)% increased Mana Reservation Efficiency of Skills',
				'Quiver: (25-29)% increased Global Critical Strike Chance',
				'Amulet: (25-29)% increased Global Critical Strike Chance',
				'Ring: (15-17)% increased Global Critical Strike Chance',
				'Belt: (21-25)% increased Stun Duration on Enemies',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9Mb2F0aGluZzQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/34e7918149/Loathing4.png',
			id: '191be0ef126398f12533103764b5811b610a8b6a5a39c305faa23823e18a7f6c',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Wailing Essence of Loathing',
			verified: false,
			w: 1,
			x: 76,
			y: 0,
		},
		{
			baseType: 'Muttering Essence of Hatred',
			descrText: 'Right click this item then left click a normal item to apply it.',
			explicitMods: [
				'Upgrades a normal item to rare with one guaranteed property',
				'Properties restricted to level 45 and below',
				'',
				'Bow: Adds (12-17) to (26-30) Cold Damage',
				'Two Handed Melee Weapon: Adds (12-17) to (26-30) Cold Damage',
				'Other Weapon: Adds (7-9) to (14-16) Cold Damage',
				'Armour: (12-17)% to Cold Resistance',
				'Quiver: (12-17)% to Cold Resistance',
				'Belt: (12-17)% to Cold Resistance',
				'Other Jewellery: (11-14)% increased Cold Damage',
			],
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvRXNzZW5jZS9IYXRyZWQyIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/4242033438/Hatred2.png',
			id: '05dbab9941280337c0611a8018bebdbfec0ac152f399f77d54337825def1c1d5',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Standard',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/9', 0]] }],
			stackSize: 1,
			typeLine: 'Muttering Essence of Hatred',
			verified: false,
			w: 1,
			x: 1,
			y: 0,
		},
	],
	metadata: { colour: 'cc009a' },
	name: 'E (Remove-only)',
	type: 'EssenceStash',
} satisfies TabWithItems;
