use serde::Deserialize;

use crate::error::Error;

use super::{NinjaRecord, Record};
use std::collections::HashMap;

pub const LEGACY_CARDS: [&'static str; 15] = [
    "Friendship",
    "Vile Power",
    "Squandered Prosperity",
    "Blessing of God",
    "The Devastator",
    "The Iron Bard",
    "Luck of the Vaal",
    "A Note in the Wind",
    "The Valley of Steel Boxes",
    "Akil's Prophecy",
    "Birth of the Three",
    "The Mayor",
    "The Transformation",
    "The Mad King",
    "Treasures of the Vaal",
];

pub const NAMES: [&'static str; 423] = [
    "A Dab of Ink",
    "A Familiar Call",
    "A Fate Worse Than Death",
    "A Modest Request",
    "A Mother's Parting Gift",
    "A Sea of Blue",
    "A Stone Perfected",
    "Abandoned Wealth",
    "Acclimatisation",
    "Alluring Bounty",
    "Alone in the Darkness",
    "Altered Perception",
    "Ambitious Obsession",
    "Anarchy's Price",
    "Arrogance of the Vaal",
    "Assassin's Favour",
    "Astral Protection",
    "Atziri's Arsenal",
    "Audacity",
    "Azure Rage",
    "Azyran's Reward",
    "Baited Expectations",
    "Beauty Through Death",
    "Bijoux",
    "Birth of the Three",
    "Blind Venture",
    "Boon of Justice",
    "Boon of the First Ones",
    "Boundless Realms",
    "Bowyer's Dream",
    "Broken Promises",
    "Broken Truce",
    "Brotherhood in Exile",
    "Brother's Stash",
    "Brush, Paint and Palette",
    "Buried Treasure",
    "Burning Blood",
    "Call to the First Ones",
    "Cameria's Cut",
    "Cartographer's Delight",
    "Chaotic Disposition",
    "Chasing Risk",
    "Checkmate",
    "Choking Guilt",
    "Costly Curio",
    "Council of Cats",
    "Coveted Possession",
    "Cursed Words",
    "Dark Dreams",
    "Dark Temptation",
    "Darker Half",
    "Deadly Joy",
    "Death",
    "Deathly Designs",
    "Dementophobia",
    "Demigod's Wager",
    "Desecrated Virtue",
    "Desperate Crusade",
    "Destined to Crumble",
    "Dialla's Subjugation",
    "Disdain",
    "Divine Justice",
    "Doedre's Madness",
    "Doryani's Epiphany",
    "Draped in Dreams",
    "Duality",
    "Dying Anguish",
    "Dying Light",
    "Earth Drinker",
    "Echoes of Love",
    "Emperor of Purity",
    "Emperor's Luck",
    "Endless Night",
    "Etched in Blood",
    "Eternal Bonds",
    "Fateful Meeting",
    "Forbidden Power",
    "From Bone to Ashes",
    "Further Invention",
    "Gemcutter's Mercy",
    "Gemcutter's Promise",
    "Gift of Asenath",
    "Gift of the Gemling Queen",
    "Glimmer of Hope",
    "Grave Knowledge",
    "Guardian's Challenge",
    "Harmony of Souls",
    "Haunting Shadows",
    "Her Mask",
    "Heterochromia",
    "Home",
    "Hope",
    "House of Mirrors",
    "Hubris",
    "Humility",
    "Hunter's Resolve",
    "Hunter's Reward",
    "Immortal Resolve",
    "Imperfect Memories",
    "Imperial Legacy",
    "Jack in the Box",
    "Judging Voices",
    "Justified Ambition",
    "Keeper's Corruption",
    "Lachrymal Necrosis",
    "Lantador's Lost Love",
    "Last Hope",
    "Left to Fate",
    "Lethean Temptation",
    "Light and Truth",
    "Lingering Remnants",
    "Lost Worlds",
    "Love Through Ice",
    "Loyalty",
    "Lucky Connections",
    "Lucky Deck",
    "Luminous Trove",
    "Lysah's Respite",
    "Magnum Opus",
    "Mawr Blaidd",
    "Merciless Armament",
    "Might is Right",
    "Misery in Darkness",
    "Mitts",
    "Monochrome",
    "More is Never Enough",
    "No Traces",
    "Nook's Crown",
    "Parasitic Passengers",
    "Peaceful Moments",
    "Perfection",
    "Prejudice",
    "Pride Before the Fall",
    "Pride of the First Ones",
    "Prometheus' Armoury",
    "Prosperity",
    "Rain of Chaos",
    "Rain Tempter",
    "Rats",
    "Rebirth",
    "Rebirth and Renewal",
    "Reckless Ambition",
    "Remembrance",
    "Sambodhi's Vow",
    "Sambodhi's Wisdom",
    "Scholar of the Seas",
    "Seven Years Bad Luck",
    "Shard of Fate",
    "Silence and Frost",
    "Society's Remorse",
    "Something Dark",
    "Struck by Lightning",
    "Succor of the Sinless",
    "Terrible Secret of Space",
    "The Academic",
    "The Admirer",
    "The Adventuring Spirit",
    "The Aesthete",
    "The Apothecary",
    "The Archmage's Right Hand",
    "The Arena Champion",
    "The Army of Blood",
    "The Artist",
    "The Aspirant",
    "The Astromancer",
    "The Avenger",
    "The Awakened",
    "The Bargain",
    "The Battle Born",
    "The Bear Woman",
    "The Beast",
    "The Betrayal",
    "The Bitter Blossom",
    "The Blazing Fire",
    "The Blessing of Moosh",
    "The Body",
    "The Bones",
    "The Brawny Battle Mage",
    "The Breach",
    "The Brittle Emperor",
    "The Cache",
    "The Cacophony",
    "The Calling",
    "The Card Sharp",
    "The Carrion Crow",
    "The Cartographer",
    "The Cataclysm",
    "The Catalyst",
    "The Catch",
    "The Celestial Justicar",
    "The Celestial Stone",
    "The Chains that Bind",
    "The Cheater",
    "The Chosen",
    "The Coming Storm",
    "The Conduit",
    "The Craving",
    "The Cursed King",
    "The Damned",
    "The Dapper Prodigy",
    "The Dark Mage",
    "The Darkest Dream",
    "The Deal",
    "The Deceiver",
    "The Deep Ones",
    "The Demon",
    "The Demoness",
    "The Destination",
    "The Doctor",
    "The Doppelganger",
    "The Dragon",
    "The Dragon's Heart",
    "The Dreamer",
    "The Dreamland",
    "The Drunken Aristocrat",
    "The Dungeon Master",
    "The Easy Stroll",
    "The Eldritch Decay",
    "The Emptiness",
    "The Encroaching Darkness",
    "The Endless Darkness",
    "The Endurance",
    "The Enforcer",
    "The Enlightened",
    "The Enthusiasts",
    "The Escape",
    "The Eternal War",
    "The Ethereal",
    "The Explorer",
    "The Eye of Terror",
    "The Eye of the Dragon",
    "The Fathomless Depths",
    "The Feast",
    "The Fiend",
    "The Fishmonger",
    "The Fletcher",
    "The Flora's Gift",
    "The Fool",
    "The Forgotten Treasure",
    "The Formless Sea",
    "The Forsaken",
    "The Forward Gaze",
    "The Fox",
    "The Fox in the Brambles",
    "The Gambler",
    "The Garish Power",
    "The Gemcutter",
    "The Gentleman",
    "The Gladiator",
    "The Golden Era",
    "The Greatest Intentions",
    "The Gulf",
    "The Hale Heart",
    "The Harvester",
    "The Hermit",
    "The Heroic Shot",
    "The Hive of Knowledge",
    "The Hoarder",
    "The Hook",
    "The Hunger",
    "The Immortal",
    "The Incantation",
    "The Innocent",
    "The Inoculated",
    "The Insatiable",
    "The Inventor",
    "The Jester",
    "The Jeweller's Boon",
    "The Journalist",
    "The Journey",
    "The King's Blade",
    "The King's Heart",
    "The Landing",
    "The Last One Standing",
    "The Last Supper",
    "The Leviathan",
    "The Lich",
    "The Life Thief",
    "The Lion",
    "The Long Con",
    "The Long Watch",
    "The Lord in Black",
    "The Lord of Celebration",
    "The Lover",
    "The Lunaris Priestess",
    "The Magma Crab",
    "The Master",
    "The Master Artisan",
    "The Mercenary",
    "The Messenger",
    "The Metalsmith's Gift",
    "The Mind's Eyes",
    "The Mountain",
    "The Nurse",
    "The Oath",
    "The Obscured",
    "The Offering",
    "The Offspring",
    "The Old Man",
    "The One That Got Away",
    "The One With All",
    "The Opulent",
    "The Pack Leader",
    "The Pact",
    "The Patient",
    "The Penitent",
    "The Poet",
    "The Polymath",
    "The Porcupine",
    "The Price of Devotion",
    "The Price of Loyalty",
    "The Price of Prescience",
    "The Price of Protection",
    "The Primordial",
    "The Prince of Darkness",
    "The Professor",
    "The Progeny of Lunaris",
    "The Puzzle",
    "The Queen",
    "The Rabbit's Foot",
    "The Rabid Rhoa",
    "The Realm",
    "The Risk",
    "The Rite of Elements",
    "The Road to Power",
    "The Ruthless Ceinture",
    "The Sacrifice",
    "The Saint's Treasure",
    "The Samurai's Eye",
    "The Scarred Meadow",
    "The Scavenger",
    "The Scholar",
    "The Scout",
    "The Seeker",
    "The Sephirot",
    "The Shepherd's Sandals",
    "The Shieldbearer",
    "The Shortcut",
    "The Side Quest",
    "The Sigil",
    "The Siren",
    "The Skeleton",
    "The Soul",
    "The Spark and the Flame",
    "The Spoiled Prince",
    "The Standoff",
    "The Stormcaller",
    "The Strategist",
    "The Summoner",
    "The Sun",
    "The Surgeon",
    "The Surveyor",
    "The Survivalist",
    "The Sustenance",
    "The Sword King's Salute",
    "The Thaumaturgist",
    "The Throne",
    "The Tinkerer's Table",
    "The Tireless Extractor",
    "The Tower",
    "The Traitor",
    "The Trial",
    "The Tumbleweed",
    "The Twilight Moon",
    "The Twins",
    "The Tyrant",
    "The Undaunted",
    "The Undisputed",
    "The Unexpected Prize",
    "The Union",
    "The Valkyrie",
    "The Vast",
    "The Visionary",
    "The Void",
    "The Warden",
    "The Warlord",
    "The Watcher",
    "The Web",
    "The White Knight",
    "The Whiteout",
    "The Wilted Rose",
    "The Wind",
    "The Witch",
    "The Wolf",
    "The Wolf's Legacy",
    "The Wolf's Shadow",
    "The Wolven King's Bite",
    "The Wolverine",
    "The World Eater",
    "The Wrath",
    "The Wretched",
    "Thirst for Knowledge",
    "Three Faces in the Dark",
    "Three Voices",
    "Thunderous Skies",
    "Time-Lost Relic",
    "Tranquillity",
    "Treasure Hunter",
    "Triskaidekaphobia",
    "Turn the Other Cheek",
    "Unchained",
    "Underground Forest",
    "Unrequited Love",
    "Vanity",
    "Vinia's Token",
    "Void of the Elements",
    "Volatile Power",
    "Wealth and Power",
    "Winter's Embrace",
    "Friendship",
    "Vile Power",
    "Squandered Prosperity",
    "Blessing of God",
    "The Devastator",
    "The Iron Bard",
    "Luck of the Vaal",
    "A Note in the Wind",
    "The Valley of Steel Boxes",
    "Akil's Prophecy",
    "The Mayor",
    "The Transformation",
    "The Mad King",
    "Treasures of the Vaal",
];

pub const TUP_NAMES_PRICES: &'static [(&str, f32)] = &[
    ("House of Mirrors", 11608.35),
    ("The Apothecary", 11251.17),
    ("The Price of Devotion", 5772.65),
    ("Unrequited Love", 4464.75),
    ("The Doctor", 4107.57),
    ("The Demon", 3393.21),
    ("The Fiend", 2500.26),
    ("The Immortal", 1285.85),
    ("Love Through Ice", 1232.27),
    ("The Shieldbearer", 571.49),
    ("The Nurse", 482.19),
    ("Seven Years Bad Luck", 335.0),
    ("The Cheater", 267.88),
    ("Choking Guilt", 267.88),
    ("Wealth and Power", 196.45),
    ("The Sephirot", 160.0),
    ("Succor of the Sinless", 160.0),
    ("Desecrated Virtue", 129.88),
    ("Doryani's Epiphany", 122.89),
    ("The Price of Loyalty", 101.3),
    ("The Samurai's Eye", 82.75),
    ("Brother's Stash", 75.77),
    ("The Dragon's Heart", 75.0),
    ("Deadly Joy", 60.0),
    ("The Patient", 59.0),
    ("A Fate Worse Than Death", 55.0),
    ("The Enlightened", 50.0),
    ("The Strategist", 45.0),
    ("Eternal Bonds", 40.72),
    ("Broken Promises", 40.0),
    ("Luminous Trove", 35.27),
    ("Darker Half", 34.97),
    ("The Artist", 32.0),
    ("The Gulf", 29.46),
    ("The Mind's Eyes", 29.0),
    ("Home", 27.93),
    ("The Academic", 27.0),
    ("Gemcutter's Mercy", 24.87),
    ("The Destination", 24.0),
    ("The Sacrifice", 20.0),
    ("Monochrome", 20.0),
    ("Imperfect Memories", 20.0),
    ("Magnum Opus", 19.98),
    ("The Hook", 17.48),
    ("Alluring Bounty", 16.15),
    ("Winter's Embrace", 15.42),
    ("Altered Perception", 14.77),
    ("Gift of Asenath", 13.0),
    ("The Greatest Intentions", 10.0),
    ("A Modest Request", 10.0),
    ("The Eternal War", 10.0),
    ("The Aspirant", 10.0),
    ("The Astromancer", 9.96),
    ("Justified Ambition", 9.66),
    ("Beauty Through Death", 9.5),
    ("The Fishmonger", 9.18),
    ("The Damned", 9.0),
    ("The Eye of Terror", 9.0),
    ("Fateful Meeting", 9.0),
    ("Remembrance", 8.24),
    ("The Leviathan", 8.0),
    ("The One That Got Away", 7.74),
    ("Pride of the First Ones", 7.0),
    ("The Escape", 7.0),
    ("The Bitter Blossom", 7.0),
    ("The Rabbit's Foot", 7.0),
    ("Judging Voices", 7.0),
    ("The Enforcer", 7.0),
    ("Nook's Crown", 6.0),
    ("The Sustenance", 6.0),
    ("A Familiar Call", 5.96),
    ("The Scout", 5.9),
    ("Abandoned Wealth", 5.73),
    ("Chaotic Disposition", 5.7),
    ("Something Dark", 5.05),
    ("Mawr Blaidd", 5.0),
    ("The Polymath", 5.0),
    ("The Undisputed", 5.0),
    ("The Bargain", 5.0),
    ("Azyran's Reward", 5.0),
    ("Void of the Elements", 5.0),
    ("The Old Man", 5.0),
    ("Underground Forest", 5.0),
    ("Etched in Blood", 5.0),
    ("The Eldritch Decay", 5.0),
    ("The Progeny of Lunaris", 5.0),
    ("The White Knight", 5.0),
    ("The Long Con", 5.0),
    ("Draped in Dreams", 5.0),
    ("Haunting Shadows", 5.0),
    ("The Shortcut", 5.0),
    ("Dementophobia", 5.0),
    ("The Emptiness", 5.0),
    ("Bijoux", 5.0),
    ("Duality", 5.0),
    ("Lethean Temptation", 5.0),
    ("The Vast", 4.98),
    ("Desperate Crusade", 4.89),
    ("Further Invention", 4.73),
    ("The Offering", 4.0),
    ("The Chosen", 4.0),
    ("Brotherhood in Exile", 4.0),
    ("Dying Light", 4.0),
    ("Keeper's Corruption", 4.0),
    ("Ambitious Obsession", 4.0),
    ("The Forgotten Treasure", 4.0),
    ("Chasing Risk", 4.0),
    ("The Catch", 4.0),
    ("Rebirth and Renewal", 4.0),
    ("Peaceful Moments", 3.98),
    ("The Shepherd's Sandals", 3.87),
    ("The Price of Prescience", 3.86),
    ("The Celestial Stone", 3.72),
    ("Death", 3.0),
    ("Merciless Armament", 3.0),
    ("Pride Before the Fall", 3.0),
    ("The Brittle Emperor", 3.0),
    ("The Queen", 3.0),
    ("The Risk", 3.0),
    ("The Thaumaturgist", 3.0),
    ("The Void", 3.0),
    ("Rebirth", 3.0),
    ("The World Eater", 3.0),
    ("The Dreamer", 3.0),
    ("The Hale Heart", 3.0),
    ("The Professor", 3.0),
    ("Perfection", 3.0),
    ("The Undaunted", 3.0),
    ("Boon of the First Ones", 3.0),
    ("The Seeker", 3.0),
    ("Dark Dreams", 3.0),
    ("The Side Quest", 3.0),
    ("Council of Cats", 3.0),
    ("Prometheus' Armoury", 3.0),
    ("The Tumbleweed", 3.0),
    ("The Awakened", 3.0),
    ("The Hive of Knowledge", 3.0),
    ("Brush, Paint and Palette", 3.0),
    ("The Enthusiasts", 3.0),
    ("Lachrymal Necrosis", 3.0),
    ("Costly Curio", 3.0),
    ("A Stone Perfected", 3.0),
    ("Guardian's Challenge", 3.0),
    ("The Forward Gaze", 3.0),
    ("Hunter's Reward", 2.99),
    ("The Twilight Moon", 2.99),
    ("The Endless Darkness", 2.99),
    ("Parasitic Passengers", 2.96),
    ("Silence and Frost", 2.9),
    ("The Soul", 2.84),
    ("The Deal", 2.78),
    ("The Prince of Darkness", 2.75),
    ("The Dungeon Master", 2.74),
    ("Terrible Secret of Space", 2.71),
    ("Divine Justice", 2.63),
    ("Prejudice", 2.59),
    ("The Messenger", 2.55),
    ("Audacity", 2.54),
    ("The Whiteout", 2.5),
    ("The Road to Power", 2.42),
    ("The Avenger", 2.28),
    ("Misery in Darkness", 2.26),
    ("The Tyrant", 2.25),
    ("The Life Thief", 2.17),
    ("The Brawny Battle Mage", 2.03),
    ("Bowyer's Dream", 2.0),
    ("Dying Anguish", 2.0),
    ("Emperor of Purity", 2.0),
    ("Light and Truth", 2.0),
    ("Lucky Deck", 2.0),
    ("The Body", 2.0),
    ("The Cartographer", 2.0),
    ("The Cataclysm", 2.0),
    ("The Celestial Justicar", 2.0),
    ("The Drunken Aristocrat", 2.0),
    ("The Feast", 2.0),
    ("The Hunger", 2.0),
    ("The Jester", 2.0),
    ("The Pact", 2.0),
    ("The Siren", 2.0),
    ("The Throne", 2.0),
    ("The Union", 2.0),
    ("The Valkyrie", 2.0),
    ("The Wretched", 2.0),
    ("The Wolven King's Bite", 2.0),
    ("The Saint's Treasure", 2.0),
    ("The Spark and the Flame", 2.0),
    ("No Traces", 2.0),
    ("The Obscured", 2.0),
    ("The Breach", 2.0),
    ("Immortal Resolve", 2.0),
    ("The Darkest Dream", 2.0),
    ("The Innocent", 2.0),
    ("The Cacophony", 2.0),
    ("A Dab of Ink", 2.0),
    ("Sambodhi's Vow", 2.0),
    ("The Lord of Celebration", 2.0),
    ("The Landing", 2.0),
    ("The Journey", 2.0),
    ("Burning Blood", 2.0),
    ("The Deep Ones", 2.0),
    ("Demigod's Wager", 2.0),
    ("Buried Treasure", 2.0),
    ("The Primordial", 2.0),
    ("The Heroic Shot", 2.0),
    ("Cameria's Cut", 2.0),
    ("Baited Expectations", 2.0),
    ("Deathly Designs", 2.0),
    ("The Easy Stroll", 2.0),
    ("The Unexpected Prize", 2.0),
    ("Unchained", 2.0),
    ("Society's Remorse", 2.0),
    ("The Bear Woman", 2.0),
    ("Reckless Ambition", 2.0),
    ("The Offspring", 2.0),
    ("Disdain", 2.0),
    ("The Magma Crab", 2.0),
    ("Checkmate", 2.0),
    ("Endless Night", 2.0),
    ("A Mother's Parting Gift", 1.99),
    ("The Ethereal", 1.99),
    ("Echoes of Love", 1.99),
    ("The Fool", 1.99),
    ("The Archmage's Right Hand", 1.99),
    ("Sambodhi's Wisdom", 1.99),
    ("Dialla's Subjugation", 1.9),
    ("The King's Heart", 1.89),
    ("Heterochromia", 1.84),
    ("The Warlord", 1.75),
    ("Arrogance of the Vaal", 1.74),
    ("The Incantation", 1.65),
    ("The Last One Standing", 1.6),
    ("Vinia's Token", 1.55),
    ("The Wind", 1.35),
    ("Triskaidekaphobia", 1.32),
    ("Harmony of Souls", 1.31),
    ("Lucky Connections", 1.19),
    ("The Dark Mage", 1.17),
    ("From Bone to Ashes", 1.16),
    ("More is Never Enough", 1.13),
    ("The Lord in Black", 1.05),
    ("The Gentleman", 1.02),
    ("Anarchy's Price", 1.0),
    ("Assassin's Favour", 1.0),
    ("Blind Venture", 1.0),
    ("Boundless Realms", 1.0),
    ("Cartographer's Delight", 1.0),
    ("Coveted Possession", 1.0),
    ("Destined to Crumble", 1.0),
    ("Doedre's Madness", 1.0),
    ("Earth Drinker", 1.0),
    ("Emperor's Luck", 1.0),
    ("Gemcutter's Promise", 1.0),
    ("Gift of the Gemling Queen", 1.0),
    ("Glimmer of Hope", 1.0),
    ("Grave Knowledge", 1.0),
    ("Her Mask", 1.0),
    ("Hope", 1.0),
    ("Hubris", 1.0),
    ("Humility", 1.0),
    ("Hunter's Resolve", 1.0),
    ("Jack in the Box", 1.0),
    ("Lantador's Lost Love", 1.0),
    ("Last Hope", 1.0),
    ("Lost Worlds", 1.0),
    ("Loyalty", 1.0),
    ("Lysah's Respite", 1.0),
    ("Prosperity", 1.0),
    ("Rain of Chaos", 1.0),
    ("Rain Tempter", 1.0),
    ("Rats", 1.0),
    ("Scholar of the Seas", 1.0),
    ("Shard of Fate", 1.0),
    ("The Aesthete", 1.0),
    ("The Arena Champion", 1.0),
    ("The Battle Born", 1.0),
    ("The Betrayal", 1.0),
    ("The Calling", 1.0),
    ("The Carrion Crow", 1.0),
    ("The Catalyst", 1.0),
    ("The Conduit", 1.0),
    ("The Cursed King", 1.0),
    ("The Dapper Prodigy", 1.0),
    ("The Demoness", 1.0),
    ("The Doppelganger", 1.0),
    ("The Dragon", 1.0),
    ("The Encroaching Darkness", 1.0),
    ("The Endurance", 1.0),
    ("The Explorer", 1.0),
    ("The Fletcher", 1.0),
    ("The Flora's Gift", 1.0),
    ("The Formless Sea", 1.0),
    ("The Fox", 1.0),
    ("The Gambler", 1.0),
    ("The Gemcutter", 1.0),
    ("The Gladiator", 1.0),
    ("The Harvester", 1.0),
    ("The Hermit", 1.0),
    ("The Hoarder", 1.0),
    ("The Inoculated", 1.0),
    ("The Inventor", 1.0),
    ("The King's Blade", 1.0),
    ("The Lich", 1.0),
    ("The Lion", 1.0),
    ("The Lover", 1.0),
    ("The Lunaris Priestess", 1.0),
    ("The Mercenary", 1.0),
    ("The Metalsmith's Gift", 1.0),
    ("The Oath", 1.0),
    ("The One With All", 1.0),
    ("The Pack Leader", 1.0),
    ("The Penitent", 1.0),
    ("The Poet", 1.0),
    ("The Rabid Rhoa", 1.0),
    ("The Scarred Meadow", 1.0),
    ("The Scavenger", 1.0),
    ("The Scholar", 1.0),
    ("The Sigil", 1.0),
    ("The Spoiled Prince", 1.0),
    ("The Stormcaller", 1.0),
    ("The Summoner", 1.0),
    ("The Sun", 1.0),
    ("The Surgeon", 1.0),
    ("The Surveyor", 1.0),
    ("The Survivalist", 1.0),
    ("The Tower", 1.0),
    ("The Traitor", 1.0),
    ("The Trial", 1.0),
    ("The Twins", 1.0),
    ("The Visionary", 1.0),
    ("The Warden", 1.0),
    ("The Watcher", 1.0),
    ("The Web", 1.0),
    ("The Wolf", 1.0),
    ("The Wolf's Shadow", 1.0),
    ("The Wrath", 1.0),
    ("Three Faces in the Dark", 1.0),
    ("Thunderous Skies", 1.0),
    ("Time-Lost Relic", 1.0),
    ("Tranquillity", 1.0),
    ("Treasure Hunter", 1.0),
    ("Turn the Other Cheek", 1.0),
    ("Volatile Power", 1.0),
    ("Mitts", 1.0),
    ("Call to the First Ones", 1.0),
    ("Lingering Remnants", 1.0),
    ("The Coming Storm", 1.0),
    ("The Wolverine", 1.0),
    ("The Garish Power", 1.0),
    ("The Standoff", 1.0),
    ("The Porcupine", 1.0),
    ("The Forsaken", 1.0),
    ("Might is Right", 1.0),
    ("Atziri's Arsenal", 1.0),
    ("The Opulent", 1.0),
    ("Struck by Lightning", 1.0),
    ("The Blazing Fire", 1.0),
    ("The Ruthless Ceinture", 1.0),
    ("The Eye of the Dragon", 1.0),
    ("The Realm", 1.0),
    ("Left to Fate", 1.0),
    ("The Deceiver", 1.0),
    ("The Puzzle", 1.0),
    ("The Insatiable", 1.0),
    ("Forbidden Power", 1.0),
    ("Three Voices", 1.0),
    ("The Jeweller's Boon", 1.0),
    ("The Army of Blood", 1.0),
    ("The Beast", 1.0),
    ("The Sword King's Salute", 1.0),
    ("The Master", 1.0),
    ("The Fathomless Depths", 1.0),
    ("The Rite of Elements", 1.0),
    ("The Dreamland", 1.0),
    ("The Admirer", 1.0),
    ("The Witch", 1.0),
    ("The Wilted Rose", 1.0),
    ("The Price of Protection", 1.0),
    ("The Master Artisan", 1.0),
    ("Alone in the Darkness", 1.0),
    ("Dark Temptation", 1.0),
    ("The Golden Era", 1.0),
    ("Boon of Justice", 1.0),
    ("Vanity", 1.0),
    ("Thirst for Knowledge", 1.0),
    ("The Mountain", 1.0),
    ("The Skeleton", 1.0),
    ("The Wolf's Legacy", 1.0),
    ("The Bones", 1.0),
    ("The Craving", 1.0),
    ("The Tinkerer's Table", 1.0),
    ("The Journalist", 1.0),
    ("The Cache", 1.0),
    ("Cursed Words", 1.0),
    ("The Long Watch", 1.0),
    ("Acclimatisation", 1.0),
    ("The Adventuring Spirit", 1.0),
    ("The Card Sharp", 1.0),
    ("The Last Supper", 1.0),
    ("A Sea of Blue", 1.0),
    ("The Blessing of Moosh", 1.0),
    ("The Fox in the Brambles", 1.0),
    ("The Tireless Extractor", 1.0),
    ("Astral Protection", 1.0),
    ("Azure Rage", 1.0),
    ("Broken Truce", 1.0),
    ("The Chains that Bind", 0.98),
    ("Imperial Legacy", 0.45),
];

pub fn create_starter_hashmap(
    tup_names_prices: Vec<(String, f32)>,
) -> HashMap<&'static str, Record> {
    let mut map = HashMap::<&'static str, Record>::new();

    for name in NAMES {
        let mut record = Record::default();
        record.name = name.to_string();
        map.insert(name, record);

        map.insert(
            name,
            Record {
                name: name.into(),
                ..Default::default()
            },
        );
    }

    for (name, price) in tup_names_prices {
        let mut record = match map.get_mut(&*name) {
            Some(record) => record,
            None => {
                tracing::error!("Could not get record. Name: {}.", name);
                panic!();
            }
        };
        record.calculated = Some(price);
    }

    map
}

pub fn dummy_tup_names_prices() -> Vec<(String, f32)> {
    let mut v: Vec<(String, f32)> = vec![];
    for (name, price) in TUP_NAMES_PRICES {
        v.push((name.to_string(), *price));
    }

    v
}

pub fn names_prices_from_json(string_json: &str) -> Vec<(String, f32)> {
    #[derive(Deserialize)]
    struct NinjaResponse {
        lines: Vec<NinjaRecord>,
    }

    let ninja_response: NinjaResponse = serde_json::from_str(string_json).unwrap();
    let ninja_records: Vec<NinjaRecord> = ninja_response.lines;
    let mut tuples_vector: Vec<(String, f32)> = vec![];
    for record in ninja_records {
        tuples_vector.push((record.name, record.calculated));
    }

    tuples_vector
}

pub async fn fetch_div_prices() -> Result<String, Error> {
    let client = reqwest::Client::new();
    let url =
        "https://poe.ninja/api/data/itemoverview?league=Kalandra&type=DivinationCard&language=en";
    let json = client.get(url).send().await?.text().await?;
    Ok(json)
}

/*
pub async fn read_json(json_path: &str) -> Result<String, Error> {
    let json = match std::fs::read_to_string(json_path) {
        Ok(json) => {
            // check file age
            let metadata = match std::fs::metadata(json_path) {
                Ok(metadata) => metadata,
                Err(_) => {
                    todo!()
                }
            };
            todo!()
        }
        Err(_) => {
            // download json
            match download_json().await {
                Ok(json) => todo!(),
                Err(err) => todo!(),
            }
        }
    };
}

*/

pub fn is_legacy_card(s: &str) -> bool {
    LEGACY_CARDS.contains(&s)
}
