[package]
name = "poe_data"
version = "0.1.0"
edition = "2024"

[dependencies]
poe_data_tools = { git = "https://github.com/shonya3/poe_data_tools.git" }
anyhow = "1"
arrow-array = "56"
arrow-schema = "56"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
dirs = "6"
csv = "1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
regex = "1"
slug = "0.1"
dotenv = "0.15"
futures = "0.3"
divcord = { path = "../divcord" }
card_element = { path = "../card_element" }
divi = { path = "../divi" }
googlesheets = { path = "../googlesheets" }
fs_cache_fetcher = { path = "../fs_cache_fetcher" }

[[bin]]
name = "dump"
path = "src/main.rs"
