pub const WEIGHT_SPREADSHEET_ID: &str = "1PmGES_e1on6K7O5ghHuoorEjruAVb7dQ5m7PGrW7t80";
pub const SHEET_RANGES_3_26: &[&str] = &["3.26!H3:H", "3.26!S3:S"];
pub const SHEET_RANGES_3_25: &[&str] = &["3.25!F3:F", "3.25!Q3:Q"];
pub const SHEET_RANGES_3_24: &[&str] = &["3.24!D3:D", "3.24!O3:O"];
pub const SHEET_RANGES_PRE_REWORK: &[&str] = &["3.23!D3:D", "3.23!P3:P"];
pub const WIKI_API_URL: &str = "https://www.poewiki.net/w/api.php";
pub const POEDB_MAPS_URL: &str = "https://poedb.tw/us/Maps#MapsItem";
pub const POEDB_URL: &str = "https://poedb.tw";
pub const MAPBOSSES_POEWIKI_URL: &str = "https://www.poewiki.net/wiki/Map_bosses";
