pub const BOSS_NAMES: &'static [&'static str] = &[
    "Pirate Treasure",
    "Thorn",
    "Fairgraves, Never Dying",
    "Tormented Temptress (Whakawairua Tuahu)",
    "Avatar of the Huntress",
    "Rose",
    "Nightmare's Omen",
    "Caer Blaidd, Wolfpack's Den",
    "Helial, the Day Unending",
    "Ghorr, the Grasping Maw",
    "The Vindicated Queen",
    "Kurgal, the Blackblooded",
    "Aul, the Crystal King",
    "The Infinite Hunger",
    "Fenumus, First of the Night",
    "Infector of Dreams",
    "Tahsin, Warmaker",
    "Stone of the Currents",
    "Nightmare's Omen",
    "Fragment of Winter",
    "Gorulis, Will-Thief (Infested Valley)",
    "Titan of the Grove",
    "Calderus",
    "Avatar of the Skies",
    "Avatar of Undoing",
    "Varhesh, Shimmering Aberration",
    "Erebix, Light's Bane",
    "Lord of the Hollows",
    "Messenger of the Hollows",
    "Champion of the Hollows",
    "Entity of the Void",
    "Opid, Helial's Herald",
    "Skullbeak",
    "Headmistress Braeta",
    "Eyepecker",
    "Gorulis, Will-Thief",
    "Mephod, the Earth Scorcher",
    "Ara, Sister of Light",
    "Flesh Sculptor",
    "Corpse Stitcher",
    "Nightwane",
    "The Animal Pack",
    "Stonebeak, Battle Fowl",
    "Jorus, Sky's Edge",
    "Shrieker Eihal",
    "Gisale, Thought Thief",
    "K'aj Y'ara'az",
    "Uul-Netol, Unburdened Flesh",
    "Olof, Son of the Headsman",
    "Chayula, Who Dreamt",
    "Farrul, First of the Plains",
    "Uhtred, Covetous Traitor",
    "Omniphobia, Fear Manifest",
    "Kosis, The Revelation",
    "Merveil, the Reflection (Underground Sea)",
    "Avatar of the Forge",
    "Eater of Souls",
    "The Cleansing Light",
    "Xixic, High Necromancer",
    "Armala, the Widow",
    "Ambrius, Legion Slayer",
    "Drek, Apex Hunter",
    "Bazur",
    "Prodigy of Darkness",
    "Shavronne the Sickening",
    "Amalgam of Nightmares",
    "Leo, Wolf of the Pits",
    "The High Templar",
    "The Bone Sculptor",
    "The Maven",
    "Oshabi, Avatar of the Grove",
    "Beast of the Pits",
    "Tolman, the Exhumer",
    "Burtok, Conjurer of Bones",
    "K'aj Q'ura",
    "The Brittle Emperor",
    "Uber Elder",
    "The Searing Exarch",
    "Catarina, Master of Undeath",
    "Gnar, Eater of Carrion",
    "Argus",
    "The Hallowed Husk",
    "The Cursed King",
    "The Eater of Worlds",
    "Drought-Maddened Rhoa",
    "Doedre the Defiler",
    "Khor, Sister of Shadows",
    "Murgeth Bogsong",
    "Stalker of the Endless Dunes",
    "Telvar, the Inebriated",
    "Nassar, Lion of the Seas",
    "Venarius",
    "Void Anomaly",
    "Maligaro the Mutilator",
    "Merveil, the Returned",
    "The Elder",
    "Ryslatha, the Puppet Mistress",
    "Voll, Emperor of Purity",
    "Portentia, the Foul",
    "Portentia, the Foul (Waste Pool)",
    "Erythrophagia (Phantasmagoria)",
    "Erythrophagia",
    "Hephaeus, The Hammer",
    "Selenia, the Endless Night",
    "The Brine King's Reef",
    "K'tash, the Hate Shepherd",
    "Prodigy of Hexes",
    "Excellis Aurafix",
    "Guardian of the Vault",
    "Terror of the Infinite Drifts",
    "The Eroding One",
    "The Winged Death",
    "Elida Blisterclaw (Bramble Valley)",
    "Fire and Fury (Lava Chamber)",
    "Merveil, the Reflection (Maelstrom of Chaos)",
    "Shock and Horror (Mineral Pools)",
    "Steelpoint the Avenger",
    "The Sanguine Siren",
    "K'aj A'alai (Vaal Temple Trio)",
    "The Dishonoured Queen",
    "Steelpoint the Avenger",
    "Mirage of Bones",
    "Lord of the Ashen Arrow",
    "Kitava, The Destroyer (The Destroyer's Heart)",
];

pub fn poedb_page_url(boss: &str) {
    let name = boss.split("(").next().unwrap().trim();
    let name = name.replace(" ", "_");
    let name = name.replace(",", "%2C");
    format!("https://poedb.tw/us/{name}");
}

pub const AREA_NAMES: &'static [&'static str] = &["The Apex of Sacrifice", "The Alluring Abyss"];

pub const ACT_AREA_NAMES: &'static [&'static str] = &[
    "The High Gardens",
    "The Imperial Gardens",
    "The Oasis",
    "The Marketplace",
    "The Quay",
    "The Reliquary (A5/A10)",
    "The Solaris Temple Level 1/2 (A8)",
    "The Harbour Bridge",
    "The Northern Forest (A7)",
    "The Dread Thicket (A7)",
    "Reliquary",
    "The Catacombs",
    "The Ossuary (A5/A10)",
    "The Solaris Temple Level 1/2 (A8)",
    "The Harbour Bridge",
    "The Foothills",
    "The Oasis",
    "The Vastiri Desert",
    "The Chamber of Sins Level 1/2 (A7)",
    "The Imperial Gardens",
    "The High Gardens",
    "The Ebony Barracks",
    "The Lunaris Concourse",
    "The Cavern of Anger (A6)",
    "The Crypt (A7)",
    "The Ossuary (A5/A10)",
    "The Catacombs",
    "The Aqueduct",
    "The Blood Aqueduct",
    "The Sarn Ramparts",
    "The Riverways (A6)",
    "The Southern Forest (A6)",
    "The Docks",
    "The Ebony Barracks",
    "The Grain Gate",
    "The Grand Promenade",
    "The Harbour Bridge",
    "The Lunaris Concourse",
    "The Quay",
    "The Sarn Ramparts",
    "The Slums",
    "The Solaris Concourse",
    "The City of Sarn",
    "The Battlefront",
    "The Marketplace",
    "Chamber of Innocence (A5/A10)",
    "The Beacon",
    "The Coast (A6)",
    "The Tidal Island (A6)",
    "The Twilight Strand (A6)",
    "The Mud Flats (A6)",
    "The Upper Sceptre of God",
    "The Den (A7)",
    "The Ossuary (A5/A10)",
    "The Reliquary (A5/A10)",
    "The Ascent",
    "The Descent",
    "The High Gardens",
    "The Grain Gate",
    "The Ashen Fields",
    "The Bath House",
    "The Battlefront",
    "The Beacon",
    "The Blood Aqueduct",
    "The Broken Bridge",
    "The Control Blocks",
    "The Crypt",
    "The Crystal Veins",
    "The Desecrated Chambers",
    "The Foothills",
    "The Harbour Bridge",
    "The Oasis",
    "The Ossuary",
    "The Quarry",
    "The Ravaged Square",
    "The Reliquary",
    "The Ruined Square",
    "The Slave Pens",
    "The Solaris Temple Level 1 (A3)",
    "The Temple of Decay Level 2",
    "The Vastiri Desert",
    "The Chamber of Sins Level 1/2 (A7)",
    "The Lunaris Temple Level 2 (A3/A8)",
    "Kaom's Stronghold",
    "Kaom's Dream",
    "The Belly of the Beast (A4/A9)",
    "The Battlefront",
    "The Ebony Barracks",
    "The Imperial Gardens",
    "The Aqueduct",
    "The Ascent",
    "Oriath Square",
    "The Grand Promenade",
    "The Blood Aqueduct",
    "The Temple of Decay Level 1/2",
    "The Ancient Pyramid",
    "The Vaal City",
    "The Causeway",
    "The Crypt (A7)",
    "Control BLocks",
    "Shavronne's Tower",
    "The Slave Pens",
    "Chamber of Sins Level 1/2 (A7)",
    "The Grand Arena",
    "The Crossroads (A7)",
    "The Boiling Lake",
    "The Toxic Conduits",
    "The Chamber of Sins Level 1/2 (A7)",
    "The Slums",
    "The Sarn Ramparts",
    "The Grain Gate",
    "The Imperial Fields",
    "The Crossroads (A7)",
    "The Ashen Fields",
    "The Broken Bridge",
    "The Causeway",
    "The Crossroads (A7)",
    "The Fellshrine Ruins (A7)",
    "The Northern Forest (A7)",
    "The Vaal City",
    "Maligaro's Sanctum",
    "The Belly of the Beast (A4/A9)",
    "The Harvest",
    "The Rotting Core",
    "The Chamber of Innocence",
    "The Rotting Core",
    "The Temple of Decay Level 1/2",
    "Lunaris Temple Level 1/2 (A8)",
    "The Broken Bridge",
    "The Coast (A6)",
    "The Karui Fortress",
    "The Mud Flats (A6)",
    "The Ascent",
    "The Descent",
    "Shavronne's Tower",
    "The Harvest",
    "The Rotting Core",
    "The Harvest",
    "The Rotting Core",
    "The Belly of the Beast",
    "The Rotting Core",
    "The Quay",
    "The Marketplace",
    "The Quay",
    "The Reliquary (A5/A10)",
    "The High Gardens",
    "The High Gardens",
    "The Ascent",
    "The Descent",
    "The Foothills",
    "The Ashen Fields",
    "The Imperial Fields",
    "The Library",
    "The Archives",
    "The Ruined Square",
    "The Torched Courts (A5/A10)",
    "The Crematorium",
    "The Ravaged Square",
    "Lower Prison (A6)",
    "The Crematorium",
    "The Catacombs",
    "Shavronne's Tower",
    "The Chamber of Sins Level 1 (A7)",
    "The Harbour Bridge",
    "The Solaris Temple Level 1 (A8)",
    "The Solaris Temple Level 2 (A8)",
    "The Cavern of Anger (A6)",
    "The Grand Arena",
    "Daresso's Dream",
    "Shavronne's Tower",
    "The Sceptre of God",
    "The Upper Sceptre of God",
    "The Sarn Ramparts",
    "The Solaris Concourse",
    "The Battlefront",
    "The Fellshrine Ruins (A7)",
    "Shavronne's Tower",
    "The Control Blocks (A5)",
    "The Lower Prison (A6)",
    "The Slave Pens",
    "The Quarry",
    "The Tunnel",
    "Prisoner's Gate (A6)",
    "The Feeding Trough",
    "The Cathedral Rooftop (A5)",
    "The Archives",
    "The Library",
    "The Grain Gate",
    "The Refinery",
    "Shavronne's Tower",
    "The Twilight Strand (A6)",
    "The Ashen Fields",
    "The Library",
    "The Temple of Decay Level 1",
    "The Rotting Core",
    "The Sewers",
    "The Crystal Veins",
    "The Mines Level 1",
    "The Mines Level 2",
    "The Quarry",
    "The Tunnel",
    "The Grain Gate",
    "The Refinery",
];

pub const CHESTS: &'static [&'static str] = &[
    "Light Jewellery chest (Primeval Ruins, Abyssal City, Vaal Outpost)",
    "Delve Gem Chests",
    "Uber Labyrinth/Enriched Labyrinth (Izaro's Treasure, Labyrinth Trove, Curious Lockbox)",
];
